---
# https://docs.openshift.com/container-platform/4.17/installing/installing_openstack/deploying-openstack-with-rootVolume-etcd-on-local-disk.html
- name: Load machineconfig 98-var-lib-etcd
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', '../files/98-var-lib-etcd.yaml') | from_yaml }}"

- name: Wait for the MCP to finish the cluster updates
  ansible.builtin.include_role:
    name: tools_cluster_checks
    tasks_from: wait_mcp_updated.yml
  vars:
    wait_retries: 60
    wait_delay: 60

- name: Active wait until all the ClusterOperators are ready
  ansible.builtin.include_role:
    name: tools_cluster_checks
    tasks_from: wait_until_cluster_operators_ready.yml

- name: Wait until OCP cluster is healthy
  ansible.builtin.include_role:
    name: tools_cluster_checks
    tasks_from: wait_until_cluster_is_healthy.yml

- name: Get OCP master nodes
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: Node
    label_selectors:
      - node-role.kubernetes.io/master
  register: masters
  until: masters.resources | length == 3

- name: Store the OCP master nodes names
  ansible.builtin.set_fact:
    ocp_masters: "{{ masters | json_query('resources[*].metadata.name') | list }}"

- name: Confirm that there is a disk on masters pointing to /var/lib/etcd
  ansible.builtin.shell: |
    set -o pipefail && \
    oc debug node/{{ item }} -- chroot /host lsblk | grep /var/lib/etcd
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop: "{{ ocp_masters }}"
  changed_when: false

- name: Confirm that units ended successfully (return rc 0)
  vars:
    units: # From files/98-var-lib-etcd.yaml
      - var-lib-etcd.mount
      - migrate-to-local-etcd.service
      - relabel-var-lib-etcd.service
  ansible.builtin.shell: |
    set -o pipefail && \
    oc debug node/{{ item }} -- chroot /host systemctl status {{ units | join(' ') }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop: "{{ ocp_masters }}"
  changed_when: false
