---
clouds_yaml_file_path: "{{ home_dir }}/.config/openstack/clouds.yaml"
admin_verify_cacert: false
project:
  name: "{{ user_cloud }}"
  user: user
  password: redhat
  role: member
  swift_role: member # Should be updated (to swiftoperator?) as soon https://issues.redhat.com/browse/OSPRH-1308 is done.
  domain_name: Default
  region: 'regionOne'
  os_quota:   # https://github.com/openshift/installer/tree/master/docs/user/openstack#openstack-requirements
    ram: 147456
    cores: 50
    network: 250
    subnet: 250
    security_group: 250
    security_group_rule: 1000
    port: 1510
    volumes: 100
    snapshots: 100
    gigabytes: 1000
    load_balancers: 1000
    load_balancer_listeners: 5000
    load_balancer_pools: 5000
ocp_api_description: "API {{ ocp_cluster_name }}.{{ user_cloud }}.com"
ocp_apps_description: "APPS {{ ocp_cluster_name }}.{{ user_cloud }}.com"
etc_hosts_entries:
  - {regex: 'api\..*\.shiftstack.com', row: '{{ api_fip }} api.{{ ocp_cluster_name }}.shiftstack.com'}
  - {regex: 'oauth-openshift.apps\..*\.shiftstack.com', row: '{{ apps_fip }} oauth-openshift.apps.{{ ocp_cluster_name }}.shiftstack.com'}
  - {regex: 'console-openshift-console.apps\..*\.shiftstack.com', row: '{{ apps_fip }} console-openshift-console.apps.{{ ocp_cluster_name }}.shiftstack.com'}
  - {regex: 'downloads-openshift-console.apps\..*\.shiftstack.com', row: '{{ apps_fip }} downloads-openshift-console.apps.{{ ocp_cluster_name }}.shiftstack.com'}
  - {regex: 'canary-openshift-ingress-canary.apps\..*\.shiftstack.com', row: '{{ apps_fip }} canary-openshift-ingress-canary.apps.{{ ocp_cluster_name }}.shiftstack.com'}
  - {regex: 'alertmanager-main-openshift-monitoring.apps\..*\.shiftstack.com', row: '{{ apps_fip }} alertmanager-main-openshift-monitoring.apps.{{ ocp_cluster_name }}.shiftstack.com'}
  - {regex: 'grafana-openshift-monitoring.apps\..*\.shiftstack.com', row: '{{ apps_fip }} grafana-openshift-monitoring.apps.{{ ocp_cluster_name }}.shiftstack.com'}
  - {regex: 'prometheus-k8s-openshift-monitoring.apps\..*\.shiftstack.com', row: '{{ apps_fip }} prometheus-k8s-openshift-monitoring.apps.{{ ocp_cluster_name }}.shiftstack.com'}
  - {regex: 'thanos-querier-openshift-monitoring.apps\..*\.shiftstack.com', row: '{{ apps_fip }} thanos-querier-openshift-monitoring.apps.{{ ocp_cluster_name }}.shiftstack.com'}
