---
project:
  name: "{{ user_cloud }}"
  user: user
  password: redhat
  role: member
  swift_role: swiftoperator
  domain_name: Default
  region: 'regionOne'
  os_quota:   # https://github.com/openshift/installer/tree/master/docs/user/openstack#openstack-requirements
    ram: 147456
    cores: 50
    network: 250
    subnet: 250
    security_group: 250
    security_group_rule: 1000
    port: 1510
    volumes: 100
    snapshots: 100
    gigabytes: 1000
    load_balancers: 1000
    load_balancer_listeners: 5000
    load_balancer_pools: 5000
ocp_api_description: "API {{ ocp_cluster_name }}.{{ user_cloud }}.local"
ocp_apps_description: "APPS {{ ocp_cluster_name }}.{{ user_cloud }}.local"
ocp_bootstrap_fip_description: "Bootstrap {{ ocp_cluster_name }}.{{ user_cloud }}.local"
etc_hosts_entries:
  - {regex: 'api\..*\.{{ user_cloud }}.local', row: '{{ api_ip }} api.{{ ocp_cluster_name }}.{{ user_cloud }}.local'}
  - {regex: 'oauth-openshift.apps\..*\.{{ user_cloud }}.local', row: '{{ apps_ip }} oauth-openshift.apps.{{ ocp_cluster_name }}.{{ user_cloud }}.local'}
  - {regex: 'console-openshift-console.apps\..*\.{{ user_cloud }}.local', row: '{{ apps_ip }} console-openshift-console.apps.{{ ocp_cluster_name }}.{{ user_cloud }}.local'}
  - {regex: 'downloads-openshift-console.apps\..*\.{{ user_cloud }}.local', row: '{{ apps_ip }} downloads-openshift-console.apps.{{ ocp_cluster_name }}.{{ user_cloud }}.local'}
  - {regex: 'canary-openshift-ingress-canary.apps\..*\.{{ user_cloud }}.local', row: '{{ apps_ip }} canary-openshift-ingress-canary.apps.{{ ocp_cluster_name }}.{{ user_cloud }}.local'}
  - {regex: 'alertmanager-main-openshift-monitoring.apps\..*\.{{ user_cloud }}.local', row: '{{ apps_ip }} alertmanager-main-openshift-monitoring.apps.{{ ocp_cluster_name }}.{{ user_cloud }}.local'}
  - {regex: 'grafana-openshift-monitoring.apps\..*\.{{ user_cloud }}.local', row: '{{ apps_ip }} grafana-openshift-monitoring.apps.{{ ocp_cluster_name }}.{{ user_cloud }}.local'}
  - {regex: 'prometheus-k8s-openshift-monitoring.apps\..*\.{{ user_cloud }}.local', row: '{{ apps_ip }} prometheus-k8s-openshift-monitoring.apps.{{ ocp_cluster_name }}.{{ user_cloud }}.local'}
  - {regex: 'thanos-querier-openshift-monitoring.apps\..*\.{{ user_cloud }}.local', row: '{{ apps_ip }} thanos-querier-openshift-monitoring.apps.{{ ocp_cluster_name }}.{{ user_cloud }}.local'}
