---
# defaults file for UPI
upi_inventory_file: "{{ upi_playbooks_dir }}/inventory.yaml"
upi_scripts_dir: "{{ user_cloud_installation_dir }}"
upi_github_repo_url: "https://raw.githubusercontent.com/openshift/installer/release-{{ openshift_release }}/upi/openstack/"
upi_netid_file: "{{ upi_playbooks_dir }}/netid.json"

upi_inventory_file_values:
  - {regexp: "os_subnet_range:.*", replace: "os_subnet_range: '{{ ocp_deployment_topology[openshift_topology.network_primary].machine_network.cidr }}'"}
  - {regexp: "os_external_network:.*", replace: "os_external_network: '{{ openstack_infra.external_network }}'"}
  - {regexp: "os_api_fip:.*", replace: "os_api_fip: '{{ resources.api_accessible_ip }}'"}
  - {regexp: "os_ingress_fip:.*", replace: "os_ingress_fip: '{{ resources.apps_accessible_ip }}'"}
  - {regexp: "os_bootstrap_fip:.*", replace: "os_bootstrap_fip: '{{ resources.bootstrap_fip }}'"}
  - {regexp: "ansible_python_interpreter:", replace: "#ansible_python_interpreter:"}
