---
- name: Create (if needed) API FIPs
  ansible.builtin.include_tasks: create_fip.yml
  vars:
    description: "{{ ocp_api_description }}"

- name: Get API FIP
  openstack.cloud.floating_ip_info:
    cloud: "{{ user_cloud }}"
    description: "{{ ocp_api_description }}"
    floating_network: "{{ infra.external_network }}"
    status: "down"
  register: res

- name: Store API FIP
  ansible.builtin.set_fact:
    api_fip: "{{ res.floating_ips[0].floating_ip_address }}"

- name: Create (if needed) APPS FIPs
  ansible.builtin.include_tasks: create_fip.yml
  vars:
    description: "{{ ocp_apps_description }}"

- name: Get APPS FIP
  openstack.cloud.floating_ip_info:
    cloud: "{{ user_cloud }}"
    description: "{{ ocp_apps_description }}"
    floating_network: "{{ infra.external_network }}"
    status: "down"
  register: res

- name: Store APPS FIP
  ansible.builtin.set_fact:
    apps_fip: "{{ res.floating_ips[0].floating_ip_address }}"

- name: Register Installer FIP in resources.yml
  ansible.builtin.include_role:
    name: shiftstack.tools.tools_register_resources_file
  vars:
    input:
      api_fip: "{{ api_fip }}"
      apps_fip: "{{ apps_fip }}"

- name: Add resulting API and APPS fip/vip to /etc/hosts file
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ item.regex }}"
    line: "{{ item.row }}"
    unsafe_writes: true
  vars:
    api_ip: "{{ api_fip }}"
    apps_ip: "{{ apps_fip }}"
  loop: "{{ etc_hosts_entries }}"

- name: Bootstrap fip pre-creation for UPI
  when: installation_type == 'upi'
  block:
    - name: Create the bootstrap floating IP for UPI
      ansible.builtin.shell: >
        openstack floating ip create
          --description 'Bootstrap {{ ocp_cluster_name }}.shiftstack.com' "{{ infra.external_network }}" -c name -f value
      register: bootstrap_fip
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: true

    - name: Register the bootstrap floating/virtual IP for UPI
      ansible.builtin.include_role:
        name: shiftstack.tools.tools_register_resources_file
      vars:
        input:
          bootstrap_fip: "{{ bootstrap_fip }}"
