---
- name: Create (if needed) API FIP and get the FIP info
  ansible.builtin.include_tasks: create_fip.yml
  vars:
    description: "{{ ocp_api_description }}"

- name: Store API FIP
  ansible.builtin.set_fact:
    api_fip: "{{ fip_info.floating_ips[0].floating_ip_address }}"

- name: Create (if needed) APPS FIP and get the FIP info
  ansible.builtin.include_tasks: create_fip.yml
  vars:
    description: "{{ ocp_apps_description }}"

- name: Store APPS FIP
  ansible.builtin.set_fact:
    apps_fip: "{{ fip_info.floating_ips[0].floating_ip_address }}"

- name: Register Installer FIP in resources.yml
  ansible.builtin.include_role:
    name: shiftstack.tools.tools_register_resources_file
  vars:
    input:
      api_fip: "{{ api_fip }}"
      apps_fip: "{{ apps_fip }}"

- name: Add resulting API and APPS fip/vip to /etc/hosts file
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ item.regex }}"
    line: "{{ item.row }}"
    unsafe_writes: true
  vars:
    api_ip: "{{ api_fip }}"
    apps_ip: "{{ apps_fip }}"
  loop: "{{ etc_hosts_entries }}"

- name: Bootstrap fip pre-creation for UPI
  when: installation_type == 'upi'
  block:
    - name: Create (if needed) Bootstrap FIP and get the FIP info
      ansible.builtin.include_tasks: create_fip.yml
      vars:
        description: "{{ ocp_bootstrap_fip_description }}"

    - name: Store Bootstrap FIP
      ansible.builtin.set_fact:
        bootstrap_fip: "{{ fip_info.floating_ips[0].floating_ip_address }}"

    - name: Register Installer FIPs in resources.yml
      ansible.builtin.include_role:
        name: shiftstack.tools.tools_register_resources_file
      vars:
        input:
          bootstrap_fip: "{{ bootstrap_fip }}"
