---
- name: Get the OCP release build name (it sets the 'openshift_release_build_name' fact)
  ansible.builtin.include_role:
    name: get_openshift_release
    tasks_from: get_openshift_release_build_name.yml
  vars:
    release: "{{ openshift_release }}"
    build_name: "{{ openshift_build_name }}"
    output_dir: "{{ home_dir }}"

- name: Marking the Openshift release build name {{ openshift_release_build_name }}
  ansible.builtin.debug:
    msg: "Build mark: openshift_puddle={{ openshift_release_build_name }}"

- name: Get the installer and client binaries for release {{ openshift_release_build_name }}
  ansible.builtin.include_role:
    name: get_openshift_release
    tasks_from: get_openshift_release_binaries.yml
  vars:
    binaries: [installer, client]
    release_name: "{{ openshift_release_build_name | default('') }}"
    output_dir: "{{ home_dir }}"
