---
- name: Create new Project
  ansible.builtin.include_tasks: project.yml

- name: Update clouds.yml file with new Project
  ansible.builtin.include_tasks: clouds.yml

- name: Restricted Network Preparations
  ansible.builtin.include_tasks: restricted_network.yml
  when:
    - openshift_proxy_installation

- name: Prepare setup for accessing the OCP Cluster
  ansible.builtin.include_tasks: external_access.yml

- name: Deploy and configure an installer host VM and update the inventory
  ansible.builtin.include_role:
    name: tools_installer_host
  when: deploy_installer_host
