---
- name: Create new Project
  ansible.builtin.import_tasks: project.yml

- name: Update clouds.yml file with new Project
  ansible.builtin.include_tasks: clouds.yml

- name: Prepare setup for accessing the OCP Cluster
  ansible.builtin.include_tasks: external_access.yml

- name: Get OCP installer and client in the installer host
  ansible.builtin.include_tasks: get_installer.yml
