---
- name: Create project
  openstack.cloud.project:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{ user_cloud }}"
    domain_id: default
    enabled: true
    verify: "{{ admin_verify_cacert }}"

- name: Create openstack user
  openstack.cloud.identity_user:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{ project.user }}"
    password: "{{ project.password }}"
    default_project: "{{ user_cloud }}"
    domain: default
    verify: "{{ admin_verify_cacert }}"

- name: Create openstack user role
  openstack.cloud.role_assignment:
    cloud: "{{ admin_cloud }}"
    user: "{{ project.user }}"
    role: "{{ project.role }}"
    project: "{{ user_cloud }}"
    verify: "{{ admin_verify_cacert }}"

- name: Add swift operator role to openstack user
  openstack.cloud.role_assignment:
    cloud: "{{ admin_cloud }}"
    user: "{{ project.user }}"
    role: "{{ project.swift_role }}"
    project: "{{ user_cloud }}"
    verify: "{{ admin_verify_cacert }}"

- name: Update Project Quota
  openstack.cloud.quota:
    cloud: "{{ admin_cloud }}"
    name: "{{ user_cloud }}"
    ram: "{{ project.os_quota.ram | default(omit) }}"
    cores: "{{ project.os_quota.cores | default(omit) }}"
    network: "{{ project.os_quota.network | default(omit) }}"
    subnet: "{{ project.os_quota.subnet | default(omit) }}"
    security_group: "{{ project.os_quota.security_group | default(omit) }}"
    security_group_rule: "{{ project.os_quota.security_group_rule | default(omit) }}"
    port: "{{ project.os_quota.port | default(omit) }}"
    volumes: "{{ project.os_quota.volumes | default(omit) }}"
    snapshots: "{{ project.os_quota.snapshots | default(omit) }}"
    gigabytes: "{{ project.os_quota.gigabytes | default(omit) }}"
    verify: "{{ admin_verify_cacert }}"

- name: Create flavors
  openstack.cloud.compute_flavor:
    cloud: "{{ admin_cloud | default(omit) }}"
    state: present
    name: "{{ item.value.name }}"
    ram: "{{ item.value.ram }}"
    vcpus: "{{ item.value.vcpus }}"
    disk: "{{ item.value.disk }}"
    ephemeral: "{{ item.value.ephemeral | default(omit) }}"
    verify: "{{ admin_verify_cacert }}"
  register: flavors
  loop: "{{ lookup('ansible.builtin.dict', ocp_deployment_topology.flavors) }}"
