---
- name: Discover pre-created FIPs stored on /etc/hosts
  ansible.builtin.set_fact:
    precreated_api_fip: "{{ lookup('file', '/etc/hosts').splitlines() |
                      select('search', api_filter) |
                      first | split() | first }}"
    precreated_ingress_fip: "{{ lookup('file', '/etc/hosts').splitlines() |
                      select('search', ingress_filter) |
                      first | split() | first }}"
  vars:
    api_filter: "api.{{ ocp_cluster_name }}.{{ ocp_base_domain }}"
    ingress_filter: "oauth-openshift.apps.{{ ocp_cluster_name }}.{{ ocp_base_domain }}"

- name: Generate OpenShift install-config.yaml file for IPI in non-proxy deployments
  when:
    - installation_type == 'ipi'
    - not openshift_proxy_installation
  ansible.builtin.include_tasks: install_config_generation/ipi_install_config.yml

- name: Generate OpenShift install-config.yaml file for UPI
  when: installation_type == 'upi'
  ansible.builtin.include_tasks: install_config_generation/upi_install_config.yml

- name: Generate OpenShift install-config.yaml file for IPI in proxy deployments
  when:
    - installation_type == 'ipi'
    - openshift_proxy_installation
  ansible.builtin.include_tasks: install_config_generation/proxy_install_config.yml

- name: Copy the install-config.yaml to installation dir
  ansible.builtin.copy:
    src: "{{ user_cloud_installation_dir }}/install-config.yaml"
    dest: "{{ ocp_installation_dir }}/install-config.yaml"
    remote_src: yes
    mode: u=rwx,g=rwx,o=rwx
