---
- name: Install OpenShift cluster using openshift-install
  block:
    - name: Install Openshift
      ansible.builtin.shell: |
          openshift-install create cluster --log-level debug --dir {{ ocp_installation_dir }}
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: true
  rescue:
    - name: Use an openshift-install flag to wait until the cluster is ready
      ansible.builtin.shell: |
        openshift-install wait-for install-complete --log-level debug --dir {{ ocp_installation_dir }}
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: true

    - name: Remove the bootstrap resources after the OCP installation succeeded
      ansible.builtin.shell: |
        openshift-install destroy bootstrap --log-level debug --dir {{ ocp_installation_dir }}
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: true

    - name: Mark the openshift tests as UNSTABLE
      ansible.builtin.include_role:
        name: tools_stage_results
        tasks_from: mark_stage_unstable.yml
      vars:
        unstable_msg: >-
          The openshift installation passed but unexpectedly needed the wait-for flag.
          More info in Jira KURYRQE-1002.
  always:
    - name: Synchronize artifacts from the Ansible Managed Node to Ansible Controller
      ansible.posix.synchronize:
        src: "{{ artifacts_dir }}"
        dest: "{{ controller_home_dir }}"
        mode: pull
        recursive: yes
        times: false
        perms: false
