---
- name: Discover pre-created FIPs stored on /etc/hosts
  ansible.builtin.set_fact:
    precreated_lb_fip: "{{ lookup('file', '/etc/hosts').splitlines() |
                      select('search', api_filter) |
                      first | split() | first }}"
    precreated_ingress_fip: "{{ lookup('file', '/etc/hosts').splitlines() |
                      select('search', ingress_filter) |
                      first | split() | first }}"
  vars:
    api_filter: "api.{{ ocp_cluster_name }}.{{ user_cloud }}.com"
    ingress_filter: "oauth-openshift.apps.{{ ocp_cluster_name }}.{{ user_cloud }}.com"

- name: Generate install-config.yaml from template
  ansible.builtin.template:
    src: install-config.yaml.j2
    dest: "{{ home_dir }}/install-config.yaml"
    mode: u=rw,g=rw,o=r
  vars:
    installcfg_cluster_name: "{{ ocp_cluster_name }}"
    installcfg_worker_flavor: "{{ topology.flavors.worker.name }}"
    installcfg_worker_replicas: "{{ topology.replicas.worker }}"
    installcfg_master_flavor: "{{ topology.flavors.master.name }}"
    installcfg_master_replicas: "{{ topology.replicas.master }}"
    installcfg_machine_cidr: "{{ topology.machine_cidr }}"
    installcfg_network_type: "{{ openshift_network_type }}"
    installcfg_external_network: "{{ infra.external_network }}"
    installcfg_region: "{{ infra.region }}"
    installcfg_dns_servers: "{{ infra.dns_servers }}"
    installcfg_api_floating_ip: "{{ precreated_lb_fip }}"
    installcfg_ingress_floating_ip: "{{ precreated_ingress_fip }}"

- name: Copy the install-config.yaml to installation dir
  ansible.builtin.copy:
    src: "{{ home_dir }}/install-config.yaml"
    dest: "{{ installation_dir }}/install-config.yaml"
    remote_src: yes
    mode: u=rw,g=rw,o=r

- name: Install Openshift including extra wait if needed
  block:
    - name: Install Openshift
      ansible.builtin.shell: |
          openshift-install create cluster --log-level debug --dir {{ installation_dir }}
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: true

  rescue:
    - name: Wait extra time
      ansible.builtin.shell: |
        openshift-install wait-for install-complete --log-level debug --dir {{ installation_dir }}
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: true

    - name: Remove the bootstrap resources after the OCP installation succeeded
      ansible.builtin.shell: |
        openshift-install destroy bootstrap --log-level debug --dir {{ installation_dir }}
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: true

    - name: Mark the openshift tests as UNSTABLE
      ansible.builtin.include_role:
        name: tools_stage_results
        tasks_from: mark_stage_unstable.yml
      vars:
        unstable_msg: >-
          The openshift installation passed but unexpectedly needed the wait-for flag.
          More info in Jira KURYRQE-1002.
  always:
    - name: "Copy installation files to {{ artifacts_dir }}"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ artifacts_dir }}/{{ user_cloud }}/{{ ocp_cluster_name }}"
        mode: "{{ item.mode }}"
      loop:
        - {src: "{{ installation_dir }}/", mode: "0755"}
        - {src: "{{ osp_config_dir }}", mode: "0755"}
        - {src: "{{ home_dir }}/install-config.yaml", mode: "0644"}
