---
- name: Get the RHCOS image and upload it to Openstack
  ansible.builtin.include_role:
    name: tools_upi
    tasks_from: prepare_rhcos_image.yml

- name: Create the Kubernetes manifests
  ansible.builtin.include_role:
    name: tools_upi
    tasks_from: create_ocp_manifests.yml

- name: Create the Ignition config files
  ansible.builtin.include_role:
    name: tools_upi
    tasks_from: ignition_configs.yml

- name: Retrieve the ansible playbooks for resource provisioning/deprovisioning
  ansible.builtin.include_role:
    name: tools_upi
    tasks_from: retrieve_playbooks.yml

- name: Create the bootstrap ignition file and image
  ansible.builtin.include_role:
    name: tools_upi
    tasks_from: bootstrap.yml

- name: Create the masters ignition files
  ansible.builtin.include_role:
    name: tools_upi
    tasks_from: control_plane.yml

- name: Deploy the cluster
  ansible.builtin.include_role:
    name: tools_upi
    tasks_from: deploy_cluster.yml
