---
# tasks file for openstack_test
- name: Prepare openshift-test
  ansible.builtin.include_role:
    name: tools_openshift_tests
    tasks_from: prepare_openshift_tests.yml
  vars:
    repo_name: "{{ openstack_test_name }}"
    results_dir: "{{ openstack_test_results_dir }}"
    go_version_target: "{{ openstack_tests_go_version }}"

- name: Include Openstack-Test tasks
  ansible.builtin.include_tasks: run_openstack_test.yml

- name: Post openshift-test
  ansible.builtin.include_role:
    name: tools_openshift_tests
    tasks_from: post_openshift_tests.yml
  vars:
    testsuite_name: "openstack"
    key_for_filtering_results: "openstack"
    test_name: "{{ openstack_test_name }}"
    results_dir: "{{ openstack_test_results_dir }}"
