---
- name: Set artifact paths
  ansible.builtin.set_fact:
    all_tests_path: >-
      {{ openstack_test_results_dir }}/openstack_tests.txt
    allowlist_path: >-
      {{ openstack_tests_allowlist_file | ternary(openstack_test_results_dir + '/allowlist.txt', '') }}
    blocklist_path: >-
      {{ openstack_tests_blocklist_file | ternary(openstack_test_results_dir + '/blocklist.txt', '') }}
    tests_to_run_path: >-
      {{ openstack_test_results_dir }}/list_of_tests_to_run.txt

- name: Build the openstack-tests for tests in the "openstack-test" repository
  ansible.builtin.shell: |
    source {{ home_dir }}/.bashrc
    make openstack-tests
  args:
    chdir: "{{ openstack_test_dir }}"
  changed_when: true

- name: Prepare {{ all_tests_path }} file with all the tests that can be run
  ansible.builtin.shell: >
    {{ openstack_test_dir }}/openstack-tests run openshift/openstack
    --dry-run > {{ all_tests_path }}
  environment:
    OS_CLOUD: "{{ user_cloud }}"
    KUBECONFIG: "{{ kubeconfig }}"
  changed_when: true

- name: Convert the allowlist YAML files to TXT
  ansible.builtin.include_role:
    name: tools_openshift_tests
    tasks_from: convert_yaml_tests_file_to_txt.yml
  vars:
    input_tests_list: "{{ item | trim }}"
    output_tests_list: "{{ allowlist_path }}"
  with_items: "{{ openstack_tests_allowlist_file.split(',') }}"
  when: openstack_tests_allowlist_file != ''

- name: Convert the blocklist YAML files to TXT
  ansible.builtin.include_role:
    name: tools_openshift_tests
    tasks_from: convert_yaml_tests_file_to_txt.yml
  vars:
    input_tests_list: "{{ item | trim }}"
    output_tests_list: "{{ blocklist_path }}"
    yaml_format_based_on_ocp_version: true
  with_items: "{{ openstack_tests_blocklist_file.split(',') }}"
  when: openstack_tests_blocklist_file != ''

- name: Prepare the tests list to run
  shiftstack.tools.filter_tests_list:
    input_tests_file: "{{ all_tests_path }}"
    allowlist_file: "{{ allowlist_path }}"
    blocklist_file: "{{ blocklist_path }}"
    output_file: "{{ tests_to_run_path }}"

- name: Run the openshift tests
  block:
    - name: Run openstack tests
      ansible.builtin.shell: >
        {{ openstack_test_dir }}/openstack-tests run openshift/openstack
        -f {{ tests_to_run_path }}
        --output-file {{ openstack_test_results_dir }}/{{ openstack_test_name }}.log
        --junit-dir={{ openstack_test_results_dir }} > /dev/null
      environment:
        # RHOSO_KUBECONFIG and SHIFTSTACK_PASS_FILE are required for the observability test
        OS_CLOUD: "{{ user_cloud }}"
        KUBECONFIG: "{{ kubeconfig }}"
        RHOSO_KUBECONFIG: "{{ rhoso_kubeconfig }}"
        SHIFTSTACK_PASS_FILE: "{{ kubeadmin-password }}"
      changed_when: true

    - name: Check for any failed openshift tests
      ansible.builtin.shell: >
        set -o pipefail &&
        grep -e "^failed:" {{ openstack_test_results_dir }}/{{ openstack_test_name }}.log | wc -l
        || true
      register: number_of_failed_tests
      changed_when: false

    - name: Assert that there are no failed tests
      ansible.builtin.assert:
        that: number_of_failed_tests.stdout | int == 0
        fail_msg: "There are failed openshift tests"
        success_msg: "There are no openshift tests"
  rescue:
    - name: Mark the openshift tests as UNSTABLE
      ansible.builtin.include_role:
        name: tools_stage_results
        tasks_from: mark_stage_unstable.yml
      vars:
        unstable_msg: >-
          The openshift test Suite failed.

    - name: Run must-gather
      ansible.builtin.include_role:
        name: tools_must-gather
      vars:
        must_gather_suffix: "openstack-tests"
