---
- name: Set artifact paths
  ansible.builtin.set_fact:
    all_tests_path: >-
      {{ results_dir }}/openstack_tests.txt
    allowlist_path: >-
      {{ openstack_tests_allowlist_file | ternary(results_dir + '/allowlist.txt', '') }}
    blocklist_path: >-
      {{ openstack_tests_blocklist_file | ternary(results_dir + '/blocklist.txt', '') }}
    tests_to_run_path: >-
      {{ results_dir }}/list_of_tests_to_run.txt

- name: Prepare {{ all_tests_path }} file with all the tests that can be run
  ansible.builtin.shell: >
    {{ home_dir }}/openstack-test/openstack-tests run openshift/openstack
    --dry-run > {{ all_tests_path }}
  environment:
    KUBECONFIG: .kube/config
    OS_CLOUD: "{{ user_cloud }}"
  changed_when: true

- name: Convert the allowlist YAML files to TXT
  ansible.builtin.include_role:
    name: tools_openshift_tests
    tasks_from: convert_yaml_tests_file_to_txt.yml
  vars:
    input_tests_list: "{{ item | trim }}"
    output_tests_list: "{{ allowlist_path }}"
  with_items: "{{ openstack_tests_allowlist_file.split(',') }}"
  when: openstack_tests_allowlist_file != ''

- name: Convert the blocklist YAML files to TXT
  ansible.builtin.include_role:
    name: tools_openshift_tests
    tasks_from: convert_yaml_tests_file_to_txt.yml
  vars:
    input_tests_list: "{{ item | trim }}"
    output_tests_list: "{{ blocklist_path }}"
    yaml_format_based_on_ocp_version: true
  with_items: "{{ openstack_tests_blocklist_file.split(',') }}"
  when: openstack_tests_blocklist_file != ''

- name: Prepare the tests list to run
  shiftstack.tools.filter_tests_list:
    input_tests_file: "{{ all_tests_path }}"
    allowlist_file: "{{ allowlist_path }}"
    blocklist_file: "{{ blocklist_path }}"
    output_file: "{{ tests_to_run_path }}"

- name: Run the openshift tests
  block:
    - name: Run openstack tests
      ansible.builtin.shell: >
        {{ home_dir }}/openstack-test/openstack-tests run openshift/openstack
        -f {{ tests_to_run_path }}
        --output-file {{ home_dir }}/{{ results_dir }}/{{ test_name }}.log
        --junit-dir={{ home_dir }}/{{ results_dir }} > /dev/null
      environment:
        KUBECONFIG: .kube/config
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: true

    - name: Check for any failed openshift tests
      ansible.builtin.shell: >
        set -o pipefail &&
        grep -e "^failed:" {{ results_dir }}/{{ test_name }}.log | wc -l
      register: number_of_failed_tests
      changed_when: false

    - name: Assert that there are no failed tests
      ansible.builtin.assert:
        that: number_of_failed_tests.stdout | int == 0
        fail_msg: "There are failed openshift tests"
        success_msg: "There are no openshift tests"
  rescue:
    - name: Mark the openshift tests as UNSTABLE
      ansible.builtin.include_role:
        name: utils
        tasks_from: mark_stage_unstable.yml
      vars:
        unstable_msg: >-
          The openshift test Suite failed.

    - name: Run must-gather
      ansible.builtin.include_role:
        name: tools_must-gather
      vars:
        must_gather_dir_suffix: "must-gather-openstack-tests"
        fetch_to_inventory: true
