---
openshift_release: 4.16 # It can be "4.10", "4.11", etc. or "4-stable"
openshift_build_name: "candidate" # It can be an empty value "" (latest nightly), a given build
installation_type: ipi
stages:
  - cleanup
  - prepare
  - install
  - post
  - verification
  - openstack_test
  - lb_tests

ocp_deployment_topology:
  network_type: OVNKubernetes
  primary_ip_protocol: ipv4    # ipv4 or ipv6
  secondary_ip_protocol: ""    # ipv4, ipv6, or "" for single-stack
  ipv4:
    ip_version: 4
    tenant_subnet:
      cidr: 10.196.0.0/16     # CIDR for the machine network (tenant network)
    cluster_network:
      cidr: 10.128.0.0/14
      host_prefix: 23
    service_network:
      - 172.30.0.0/16
  flavors:
    master:
      name: "master"
      ram: 16384
      vcpus: 4
      disk: 25
    worker:
      name: "worker"
      ram: 8192
      vcpus: 2
      disk: 25
  replicas:
    master: 3
    worker: 2

octavia_blocker_bugs_fixed: false # Amphora-Octavia is not working in RHOSP18 until OSPRH-387 and OSPRH-399 are done
ceph_nfs_ready: false # manila-ganesha is not configured on VA-HCI for now (OSASINFRA-3413)
