---
openshift_release: "4.16"
openshift_build_name: "candidate"
openshift_network_type: OVNKubernetes
installation_type: ipi
force_cleanup: true
stages:
  - cleanup
  - prepare
  - install
  - post
  - verification
  - openstack_test

topology:
  flavors:
    master:
      name: "master"
      ram: 16384
      vcpus: 4
      disk: 30
    worker:
      name: "worker"
      ram: 8192
      vcpus: 2
      disk: 30
  replicas:
    master: 3
    worker: 0
  machine_cidr: 10.196.0.0/16
