---
openshift_release: 4.16 # It can be "4.10", "4.11", etc. or "4-stable"
openshift_build_name: "" # It can be an empty value "" (latest nightly), a given build
openshift_network_type: OVNKubernetes
installation_type: ipi
conformance_test_type: parallel
force_cleanup: true
stages:
  - cleanup
  - prepare
  - install
  - post
  - verification
  - openstack_test
  # - conformance_test
  # - cinder_csi_tests
  # - manila_csi_tests

topology:
  flavors:
    master:
      name: "master"
      ram: 16384
      vcpus: 4
      disk: 30
    worker:
      name: "worker"
      ram: 8192
      vcpus: 2
      disk: 30
  replicas:
    master: 3
    worker: 2
  machine_cidr: 10.196.0.0/16
  servergroups:
    master: "anti-affinity"
    worker: "anti-affinity"
