---
openshift_release: 4.16 # It can be "4.10", "4.11", etc. or "4-stable"
openshift_build_name: "" # It can be an empty value "" (latest nightly), a given build
installation_type: upi
deploy_installer_host: true
stages:
  - cleanup
  - prepare
  - install
  - post
  - verification
  - openstack_test
  - lb_tests

openshift_topology:
  network_type: OVNKubernetes
  network_primary: ipv4    # ipv4 or ipv6
  network_secondary: ""    # ipv4, ipv6, or "" for single-stack
  flavors:
    master:
      name: "master"
      ram: 16384
      vcpus: 4
      disk: 25
    worker:
      name: "worker"
      ram: 8192
      vcpus: 2
      disk: 25
    bootstrap:
      name: "bootstrap"
      ram: 16384
      vcpus: 4
      disk: 25
  replicas:
    master: 3
    worker: 2
  machine_cidr: 10.196.0.0/16

octavia_blocker_bugs_fixed: false # Amphora-Octavia is not working in RHOSP18 until OSPRH-387 and OSPRH-399 are done
ceph_nfs_ready: false # manila-ganesha is not configured on VA-HCI for now (OSASINFRA-3413)
