---
openshift_release: 4.17 # It can be "4.10", "4.11", etc. or "4-stable"
openshift_build_name: "" # It can be an empty value "" (latest nightly), a given build
openshift_network_type: OVNKubernetes
installation_type: ipi
conformance_test_type: parallel
stages:
  - cleanup
  - prepare
  - install
  - gpu
  - rhoai
  - post
  - verification

day2ops_procedures:
  - moving-etcd-to-ephemeral

ocp_deployment_topology:
  network_type: OVNKubernetes
  primary_ip_protocol: ipv4    # ipv4 or ipv6
  secondary_ip_protocol: ""    # ipv4, ipv6, or "" for single-stack
  ipv4:
    ip_version: 4
    tenant_subnet:
      cidr: 10.196.0.0/16     # CIDR for the machine network (tenant network)
    cluster_network:
      cidr: 10.128.0.0/14
      host_prefix: 23
    service_network:
      - 172.30.0.0/16
  flavors:
    master:
      name: "master"
      ram: 16384
      vcpus: 4
      disk: 30
      ephemeral: 10
    worker:
      name: "worker"
      ram: 32768
      vcpus: 10
      disk: 50
      extra_specs: '{"pci_passthrough:alias": "a30:1"}'
  replicas:
    master: 3
    worker: 1
  controlplane_rootvolume:
    size: 30
    types: ['__DEFAULT__', '__DEFAULT__', '__DEFAULT__']
