---
openshift_release: 4.17 # It can be "4.10", "4.11", etc. or "4-stable"
openshift_build_name: "" # It can be an empty value "" (latest nightly), a given build
openshift_network_type: OVNKubernetes
installation_type: ipi
conformance_test_type: parallel
stages:
  - cleanup
  - prepare
  - install
  - gpu
  - post
  - verification

day2ops_procedures:
  - moving-etcd-to-ephemeral

topology:
  flavors:
    master:
      name: "master"
      ram: 16384
      vcpus: 4
      disk: 30
      ephemeral: 10
    worker:
      name: "worker"
      ram: 65536
      vcpus: 10
      disk: 100
      extra_specs: '{"pci_passthrough:alias": "a30:1"}'
  replicas:
    master: 3
    worker: 1
  machine_cidr: 10.196.0.0/16
  controlplane_rootvolume:
    size: 30
    types: ['__DEFAULT__', '__DEFAULT__', '__DEFAULT__']
