---
openshift_release: 4.18
openshift_build_name: "" # It can be an empty value "" (latest nightly), a given build
installation_type: ipi

stages:
  - cleanup
  - prepare
  - install
  - post
  - verification

openshift_topology_override:
  # Single-stack IPv6 configuration
  # network_primary: Required. Set to "ipv6" for IPv6-only networking
  # network_secondary: Must be empty string for single-stack setup
  network_primary: ipv6
  network_secondary: ""
