---
- name: Get Instances, Nodes, Machines, and MachineSets information
  ignore_errors: yes # noqa: ignore-errors
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  block:
    - name: Get OCP machinesets status
      ansible.builtin.command: 'oc get machinesets -A'
      changed_when: false

    - name: Get OCP machines status
      ansible.builtin.command: 'oc get machines -A'
      changed_when: false

    - name: Register the unrunning machines
      ansible.builtin.shell: >
        set -o pipefail &&
        oc get machines -n openshift-machine-api -o json | jq -r '.items[] |
          select(.status.phase != "Running") | .metadata.name'
      changed_when: false
      register: unrunning_machines

    - name: Describe each of the unrunning machines
      ansible.builtin.command: "oc describe machines -n openshift-machine-api {{ item }}"
      changed_when: false
      loop: "{{ unrunning_machines.stdout.split() }}"

    - name: Get OCP nodes status
      ansible.builtin.command: 'oc get nodes'
      changed_when: false

    - name: Get the project's instances status
      ansible.builtin.command: 'openstack server list'
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: false

    - name: Get OCP Control Plane MachineSet status
      ansible.builtin.shell: 'oc get controlplanemachineset/cluster -n openshift-machine-api -o=jsonpath={.spec.state}'
      changed_when: false
