---
- name: Check the unready Cluster Operators
  failed_when: false
  block:
    - name: Get the Cluster Operators
      ansible.builtin.command: 'oc get clusteroperator'
      changed_when: false

    - name: Register the unready Cluster Operators
      ansible.builtin.shell: >
        set -o pipefail &&
        oc get clusteroperator -o json | jq -r 'try .items[] |
            select((.status.conditions[] | select(.type == "Available")).status == "False"
            or (.status.conditions[] | select(.type == "Progressing")).status == "True"
            or (.status.conditions[] | select(.type == "Degraded")).status == "True") | .metadata.name'
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: unready_clusteroperators
      changed_when: false

    - name: Describe each of the unready Cluster Operators
      ansible.builtin.command: "oc describe clusteroperator/{{ item }}"
      changed_when: false
      loop: "{{ unready_clusteroperators.stdout.split() }}"
