---
- name: Check the unready Pods
  ignore_errors: yes # noqa: ignore-errors
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  block:
    - name: Get the Pods
      ansible.builtin.command: 'oc get pods -A'
      changed_when: false

    - name: Register the failed pods
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        field_selectors:
          - status.phase!=Running,status.phase!=Succeeded
      register: failed_pods
      no_log: true

    - name: Set a fact for the failed pods
      ansible.builtin.set_fact:
        failed_pods_names: >-
          {{ failed_pods | json_query("resources[*].[metadata.namespace,metadata.name]") | list }}

    - name: Describe each of the unready Pods
      ansible.builtin.command: "oc describe pod -n {{ item[0] }} {{ item[1] }}"
      loop: "{{ failed_pods_names }}"
      changed_when: false
      when: failed_pods_names | length < 5

    - name: Indicate if too many pods are not ready
      ansible.builtin.debug:
        msg: |
          {{ failed_pods_names | length }} pods are not ready.
          Please check the failed pods in the logs and must-gather.
      changed_when: false
      when: failed_pods_names | length >= 5
