---
- name: Print OCP cluster info
  any_errors_fatal: false
  block:
    - name: Get osp instances
      ansible.builtin.command: "openstack server list"
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: false

    - name: Get load balancers
      ansible.builtin.command: "openstack loadbalancer list"
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: false

    - name: Get the disabled load balancers listeners
      ansible.builtin.command: "openstack loadbalancer listener list --disable -f value"
      register: osp_lbs_listeners
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      changed_when: false

    - name: Print the disabled load balancers listeners
      ansible.builtin.debug:
        msg: |
          The following load balancers are in disabled state:
          {{ osp_lbs_listeners.stdout }}
      when: osp_lbs_listeners.stdout_lines|length > 0

    - name: Collect facts about master servers
      openstack.cloud.server_info:
        cloud: "{{ user_cloud }}"
        server: "{{ ocp_cluster_name }}*master*"
      register: result
      no_log: true

    - name: Create security group rule to allow ssh to master nodes
      openstack.cloud.security_group_rule:
        cloud: "{{ user_cloud }}"
        security_group: "{{ result.openstack_servers[0].security_groups[0].name }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
      when: (result.openstack_servers | length) > 0

    - name: Create oc config directory .kube/
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: u=rwx,g=rw,o=r

    - name: Copy oc config file to .kube/ dir
      ansible.builtin.file:
        src: "{{ kubeconfig }}"
        dest: ~/.kube/config
        state: link

    - name: Gather the bootstrap logs
      when: gather_bootstrap|default(True)
      block:
        - name: Gather bootstrap logs
          ansible.builtin.shell: |
            openshift-install gather bootstrap --dir {{ ocp_cluster_name }} --log-level=debug
          environment:
            SSH_AUTH_SOCK: ""
          failed_when: false
          changed_when: true

        - name: Compress {{ installation_dir }} directory
          community.general.archive:
            path: "{{ installation_dir }}"
            dest: "{{ installation_dir }}.tar.gz"
            mode: u=rw,g=rw,o=r

        - name: Fetch {{ installation_dir }}.tar.gz to {{ artifacts_dir }}
          ansible.builtin.fetch:
            src: "{{ installation_dir }}.tar.gz"
            dest: "{{ artifacts_dir }}/failing_installation_logs.tar.gz"
            flat: yes

    - name: Get ocp cluster version
      ansible.builtin.command: oc get clusterversion
      changed_when: false

    - name: Get Instances, Machines, and MachineSets information
      ansible.builtin.include_tasks: debug_machines.yml

    - name: Get cluster operators
      ansible.builtin.command: oc get co
      changed_when: false

    - name: Get all the non available Cluster Operators
      ansible.builtin.shell: |
        set -o pipefail
        for i in $(oc get co --no-headers=true| awk '$3 != "True" {print $1}');do echo -e "\n$i\n-----------\n";oc describe co $i;done
      changed_when: false

    - name: Get pods not running or completed
      ansible.builtin.shell: |
        set -o pipefail
        oc get pods -A | grep -v -e Running -e Completed
      changed_when: false

    - name: Get all cluster pods
      ansible.builtin.command: oc get pods -A
      changed_when: false
