---
- name: Check MCP is updated
  block:
    - name: Wait 1 minute before checking nodes and MCP
      ansible.builtin.pause:
        minutes: 1

    - name: Wait for the machine config pool to finish the cluster updates
      ansible.builtin.shell: |
        oc wait --all --for=condition=Updated --timeout=1200s mcp
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      retries: "{{ wait_retries }}"
      delay: "{{ wait_delay }}"
      register: result
      until: result.rc == 0
      changed_when: false
