---
repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.22.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        name: Ansible Lint
        description: Run configurations on .ansible-lint file
        verbose: true
        # args: [-p, ./ansible/*]
        additional_dependencies:
          - jmespath

  - repo: local
    hooks:
      - id: validate-jira-commit
        name: Validate Jira Commit Message
        entry: python3 .validate_jira.py
        language: system
        stages: [commit-msg]
