---
repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v25.8.2
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        verbose: true
        args: ["--strict"] # Treat warnings as errors
        additional_dependencies:
          - jmespath

  - repo: local
    hooks:
      - id: validate-jira-commit
        name: Validate Jira Commit Message
        entry: python3 .validate_jira.py
        language: system
        stages: [commit-msg]
