---
extends: default

rules:
  line-length:
    max: 260

  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: true

  comments:
    min-spaces-from-content: 1

  document-start:
    ignore:
      - configs/secret.yaml

ignore:
  - collection/stages/roles/conformance_test/files/
