---
extends: default

rules:
  line-length:
    max: 260

  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: true

  comments:
    min-spaces-from-content: 1

  comments-indentation: false

  braces:
    max-spaces-inside: 1

  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

  document-start:
    ignore:
      - configs/secret.yaml
