---
collections:
  - name: community.general
  - name: ansible.utils
  - name: ansible.posix
  - name: openstack.cloud
    version: 2.2.0
  - name: kubernetes.core
    version: 2.3.2
  - name: ./collection/tools
  - name: ./collection/stages
