---
# tasks file for discover_ocp_version
- name: Discover running OCP release
  command: "oc --request-timeout=2s get clusterversion"
  register: oc_get_clusterversion
  ignore_errors: true

- name: Discover the running OCP network type in a case discovered a running OCP release
  block:
    - name: Discover running OCP network Type
      shell: |
        oc --request-timeout=2s get network cluster -o json \
        | jq --raw-output '.spec.networkType'
      register: oc_network

    - name: Defining discovered_openshift_release and discovered_ocp_network_type
      set_fact:
        discovered_openshift_release:
          "{{ oc_get_clusterversion.stdout_lines[-1] |
            regex_replace('version +([0-9]+.[0-9]+).*$','\\1') }}"
        discovered_ocp_network_type: "{{ oc_network.stdout }}"

    - debug:
        msg: >
          OCP Cluster with {{ discovered_openshift_release }} release
          and {{ discovered_ocp_network_type }} NetworkType discovered.
  when: oc_get_clusterversion.rc == 0
