---
- name: Restore the /etc/resolv.conf file
  become: true
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/resolv.conf.orig
    dest: /etc/resolv.conf
    mode: u=rw,g=r,o=r
    force: yes
    unsafe_writes: true

- name: Remove /etc/resolv.conf.orig
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf.orig
    state: absent

- name: Stop dnsmasq if running
  become: yes
  ansible.builtin.shell: "set -o pipefail && pkill dnsmasq || true"
  changed_when: true

- name: Remove dnsmasq
  become: true
  ansible.builtin.package:
    name: dnsmasq
    state: absent
