---
- name: Create GPU operator verification job
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: verify-cuda-vectoradd
        namespace: nvidia-gpu-operator
      spec:
        activeDeadlineSeconds: 300
        backoffLimit: 3
        template:
          spec:
            restartPolicy: OnFailure
            containers:
            - name: verify-cuda-vectoradd
              image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0-ubi8"
              resources:
                limits:
                  nvidia.com/gpu: 1

- name: Wait for verification job completed
  ansible.builtin.shell: |
    oc wait --for=condition=complete job/verify-cuda-vectoradd -n nvidia-gpu-operator --timeout=300s
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
