---
- name: Create manifests for openshift-monitoring namespace
  ansible.builtin.template:
    src: cluster-monitoring-config.yaml.j2
    dest: "{{ home_dir }}/cluster-monitoring-config.yaml"
    mode: u=rw,g=rw,o=r

- name: Apply configMap for openshift-monitoring namespace and check they are running.
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ home_dir }}/cluster-monitoring-config.yaml"
    wait: yes
    wait_timeout: 100

- name: Get the number of prometheus/k8s replicas
  ansible.builtin.shell: |
    set -o pipefail
    oc get prometheus/k8s -o json | jq .spec.replicas
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  register: prometheus_pvc_num
  changed_when: false

# Check that prometheus PVC is created on openstack
- name: Get created PVCs on openshift-monitoring
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: pvc
    namespace: "openshift-monitoring"
  register: monitoring_pvcs
  retries: 25
  delay: 15
  until:
    - monitoring_pvcs.resources|length >= prometheus_pvc_num.stdout | int
    - monitoring_pvcs|json_query('resources[*].status') is defined
    - monitoring_pvcs|json_query('resources[*].status.phase') | unique == ["Bound"]

- name: Set the monitoring PVC IDs fact
  ansible.builtin.set_fact:
    monitoring_pvc_ids: "{{ monitoring_pvcs | json_query('resources[].spec.volumeName') | list }}"

- name: Check cinder volume for PVC exist
  ansible.builtin.shell: |
    set -o pipefail
    openstack volume list -f csv | grep  {{ item }}
  environment:
    OS_CLOUD: "{{ user_cloud }}"
  changed_when: false
  loop: "{{ monitoring_pvc_ids }}"

- name: Wait until prometheus pods are recreated
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Pod
    namespace: "openshift-monitoring"
    label_selectors:
      - prometheus=k8s
    field_selectors:
      - status.phase=Running
  register: mon_pods
  retries: 40
  delay: 15
  until: mon_pods.resources|length == monitoring_pvc_ids|length
