---
# tasks file for OCP cluster verification
- name: Run verification steps
  block:
    - name: Check cluster health before the verification actions
      block:
        - name: Wait until OCP cluster is healthy
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: wait_until_cluster_is_healthy.yml

        - name: Wait until cluster nodes are ready
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: wait_until_nodes_ready.yml

        - name: Wait until there are no unschedulable nodes
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: wait_until_no_unschedulable_nodes.yml

        - name: Check the project's instances healthy
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: check_instances.yml

        - name: Check the MachineSets healthy
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: check_machinesets.yml

        - name: Check there are no pods in CrashLoopBackOff
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: check_no_crashloopbackoff.yml

        - name: Active wait until all the ClusterOperators are ready
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: wait_until_cluster_operators_ready.yml

    - name: Check the Control Plane MachineSet is healthy
      ansible.builtin.include_role:
        name: tools_cluster_checks
        tasks_from: check_controlplane_machinesets.yml
      when: not openshift_upi|default(False)

    - name: Soft Checks that can mark the installation as unstable
      when: soft_checks
      block:
        - name: Check the pods are healthy
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: check_pods.yml
          vars:
            wait_retries: 20
            wait_delay: 10

        - name: Check cluster alerts
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: check_alerts.yml

        - name: Check cluster services
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: check_nodes_services.yml

    - name: Check registry pods status
      ansible.builtin.include_tasks: check_registry.yml

    - name: Enable prometheus PVCs
      ansible.builtin.include_tasks: check_prometheus_pvcs.yml
      when:
        - bm_workers|default(False) is false

    - name: Active wait until all the ClusterOperators are ready
      ansible.builtin.include_role:
        name: tools_cluster_checks
        tasks_from: wait_until_cluster_operators_ready.yml

    - name: Create a demo app and check connectivity
      ansible.builtin.include_tasks: check_demo_app.yml

    - name: Create a LB type svc and check connectivity
      vars:
        # Using internal-lb annotation when cluster is deployed on restricted or provider network (FIPless):
        internal_lb: |
          {{ (openshift_proxy | default(False) or bm_workers | default(False) or provider_network_primary | default(False)) | bool }}
      ansible.builtin.include_tasks: check_lb_svc.yml
      when:
        - edge_nova_az is not defined # Skip due to Openstack Manila is not supported at the Edge

    - name: Run cinder checks
      ansible.builtin.include_tasks: check_cinder_csi.yml
      when:
        - bm_workers|default(False) is false

    - name: Check if manila is present on the OSP installation
      ansible.builtin.command: openstack catalog show manila -c name
      environment:
        OS_CLOUD: "{{ user_cloud }}"
      ignore_errors: yes
      register: manila_enabled
      changed_when: false

    - name: Run manila checks if it is enabled on OSP
      ansible.builtin.include_tasks: check_manila.yml
      when:
        - not openshift_upi|default(False)
        - manila_enabled.rc == 0
        - edge_nova_az is not defined # Skip due to Openstack Manila is not supported at the Edge

    - name: Check cluster health after the verification actions
      block:
        - name: Wait until OCP cluster is healthy
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: wait_until_cluster_is_healthy.yml

        - name: Wait until cluster nodes are ready
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: wait_until_nodes_ready.yml

        - name: Wait until there are no unschedulable nodes
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: wait_until_no_unschedulable_nodes.yml

        - name: Check the project's instances healthy
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: check_instances.yml

        - name: Check the MachineSets healthy
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: check_machinesets.yml

        - name: Check there are no pods in CrashLoopBackOff
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: check_no_crashloopbackoff.yml

        - name: Active wait until all the ClusterOperators are ready
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: wait_until_cluster_operators_ready.yml
  rescue:
    - name: Set the verification failed flag
      ansible.builtin.set_fact:
        verification_failed: true
        failed_task: "{{ (ansible_failed_task is defined) | ternary(ansible_failed_task.name, 'UNKNOWN') }}"

- name: Collect cluster information if any error occurred
  when: stage_unstable|default(False) or
        verification_failed|default(False)
  block:
    - name: Run must-gather
      ansible.builtin.include_role:
        name: tools_must-gather
      vars:
        fetch_to_inventory: true
        must_gather_dir_suffix: "must-gather-verification"

- name: Fail the playbook in a case of a cluster verification test failure
  ansible.builtin.fail:
    msg: >
      Failed! See logs and must-gather for more information.
      Failed task: '{{ failed_task }}'.
  when: verification_failed|default(False)
