---
- name: Restore the original '{{ hypervisor_dnsmasq_addresses_file }}'
  ansible.builtin.copy:
    src: "{{ hypervisor_dnsmasq_addresses_original_file }}"
    dest: "{{ hypervisor_dnsmasq_addresses_file }}"
    remote_src: yes

- name: Remove '{{ hypervisor_dnsmasq_addresses_original_file }}'
  ansible.builtin.file:
    path: "{{ hypervisor_dnsmasq_addresses_original_file }}"
    state: absent
