---
# tasks file for post
- name: Set the update channel to null (To avoid CannotRetrieveUpdates alert)
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      metadata:
        name: version
      spec:
        channel: ""

- name: Set the workers and masters NTP server
  ansible.builtin.include_tasks: set_ntp.yml
  when: openshift_proxy_installation

- name: Disable image Registry Operator redirects
  # To pull images directly from Red Hat OpenStack Platform (RHOSP) Swift storage
  # https://docs.openshift.com/container-platform/4.17/registry/configuring_registry_storage/configuring-registry-storage-openstack-user-infrastructure.html#registry-configuring-registry-storage-swift-trust_configuring-registry-storage-openstack-user-infrastructure
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: imageregistry.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        disableRedirect: true

- name: Add APPS DNS entry to hypervisor's dnsmasq service
  ansible.builtin.debug:
    msg: "{{ hypervisor }}"

#- name: Execute as root on {{ hypervisor }}
#  shell: whoami & hostname
#  register: cmd
#  delegate_to: "{{ hypervisor }}"
#  remote_user: zuul
#  become: true
#
#- debug:
#    var: cmd.stdout
#
#
# cat /etc/cifmw-dnsmasq.d/addresses.conf
#address=/apps.ocp.openstack.lab/x.y.z.v
#address=/apps.ostest.shiftstack.local/x.y.z.s      <<-----
