---
# tasks file for post
- name: Set the update channel to null (To avoid CannotRetrieveUpdates alert)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      metadata:
        name: version
      spec:
        channel: ""

- name: "Copy installation and Openstack files to {{ artifacts_dir }}"
  block:
    - name: "Copy installation files to {{ artifacts_dir }}"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ artifacts_dir }}/{{ user_cloud }}/{{ ocp_cluster_name }}"
        mode: "{{ item.mode }}"
      loop:
        - {src: "{{ installation_dir }}/", mode: "0755"}
        - {src: "{{ osp_config_dir }}", mode: "0755"}
        - {src: "{{ home_dir }}/install-config.yaml", mode: "0644"}
