---
# tasks file for post
- name: Set the update channel to null (To avoid CannotRetrieveUpdates alert)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      metadata:
        name: version
      spec:
        channel: ""

- name: "Copy {{ installation_dir }} to {{ artifacts_dir }}"
  ansible.builtin.copy:
    src: "{{ installation_dir }}/"
    dest: "{{ artifacts_dir }}/{{ user_cloud}}/{{ ocp_cluster_name }}"
    mode: 0755

- name: "Copy {{ installation_dir }} to {{ artifacts_dir }}"
  ansible.builtin.copy:
    src: "{{ osp_config_dir }}"
    dest: "{{ artifacts_dir }}/{{ user_cloud}}/{{ ocp_cluster_name }}"
    mode: 0755
