---
- name: Register resources in file
  ansible.builtin.blockinfile:
    content: "{{ input | to_nice_yaml }}"
    dest: "{{ resources_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ input.keys() }}"
  delegate_to: localhost
