---
- name: Create lb_allowlist_file
  ansible.builtin.copy:
    dest: "{{ lb_allowlist_file }}"
    content: "{{ lb_testfilter }}"
    mode: u=rw,g=rw,o=r

- name: Get install-config content to obtain the 1st machineCIDR
  ansible.builtin.include_role:
    name: shiftstack.tools.tools_get_deploy_info
    tasks_from: get_ic_content.yml

- name: Get the node subnet
  openstack.cloud.subnets_info:
    cloud: "{{ user_cloud }}"
    filters:
      cidr: "{{ ic_content.networking.machineNetwork[0].cidr }}"
  register: os_subnets

- name: Enable Amphora LoadBalancer with monitors and SOURCE_IP lb-method on cloud-provider-config
  ansible.builtin.include_tasks: change_cloud_cm.yml
  vars:
    octavia_provider: "amphora"
    lb_method: "SOURCE_IP"
    lb_create_monitor: "True"
    lb_monitor_delay: "{{ cloud_provider_config.lb_monitor_delay }}"
    lb_monitor_timeout: "{{ cloud_provider_config.lb_monitor_timeout }}"
    lb_monitor_max_retries: "{{ cloud_provider_config.lb_monitor_max_retries }}"
    lb_subnet_id: "{{ os_subnets.subnets[0].id }}"
    max_shared_lb: "2"
    log_directory: "{{ artifacts_dir }}/lb_amphora_sourceip"

- name: Run Openstack-Test on OCP with Amphora LoadBalancer provider and sourceIP lb method
  ansible.builtin.include_role:
    name: shiftstack.stages.openstack_test
  vars:
    openstack_test_results_dir: "{{ artifacts_dir }}/lb_amphora_sourceip"
    openstack_tests_allowlist_file: "{{ lb_allowlist_file }}"
    openstack_testsuite_name: openstack_tests_lb_amphora_sourceip
    openstack_reset_result_dir: no

- name: Enable OVN provider on cloud-provider-config
  ansible.builtin.include_tasks: change_cloud_cm.yml
  vars:
    octavia_provider: "ovn"
    lb_method: "SOURCE_IP_PORT"
    lb_create_monitor: "False"
    max_shared_lb: "2"
    log_directory: "{{ artifacts_dir }}/lb_ovn"

- name: Run Openstack-Test on OCP with OVN LoadBalancer provider
  ansible.builtin.include_role:
    name: shiftstack.stages.openstack_test
  vars:
    openstack_test_results_dir: "{{ artifacts_dir }}/lb_ovn"
    openstack_tests_allowlist_file: "{{ lb_allowlist_file }}"
    openstack_testsuite_name: openstack_tests_lb_ovn
    openstack_reset_result_dir: no
