---
blocklist: &all_block_tests
  ".*] *Networking should provide Internet connection for containers *[.*":
    note: "DNS TCP is blocked from the Lab, https://redhat.service-now.com/help?id=rh_ticket&table=sc_request&sys_id=2ef74faadbdc5950c0c8464e13961914"

# OpenShift 4.15
"4.15":
  "OVNKubernetes": &ocp415_ovn_block_tests
    <<: *all_block_tests
    ".*Feature:IPv6DualStack.*should function for service endpoints using hostNetwork.*":
      note: "Failing persistently in openshift CI"

# OpenShift 4.16
"4.16":
  "OVNKubernetes":
    <<: *ocp415_ovn_block_tests

# OpenShift 4.17
"4.17":
  "OVNKubernetes":
    <<: *ocp415_ovn_block_tests

# OpenShift 4.18
"4.18":
  "OVNKubernetes":
    <<: *ocp415_ovn_block_tests
