---
- name: Generate install-config.yaml from install-config-ipi.yaml.j2 template
  ansible.builtin.template:
    src: install-config-ipi.yaml.j2
    dest: "{{ user_cloud_installation_dir }}/install-config.yaml"
    mode: u=rw,g=rw,o=r
  vars:
    installcfg_ocp_base_domain: "{{ ocp_base_domain }}"
    installcfg_cluster_name: "{{ ocp_cluster_name }}"
    installcfg_worker_flavor: "{{ openshift_topology.flavors.worker.name }}"
    installcfg_worker_servergrouppolicy: "{{ openshift_topology.servergroups.worker | default('') }}"
    installcfg_worker_replicas: "{{ openshift_topology.replicas.worker }}"
    installcfg_master_flavor: "{{ openshift_topology.flavors.master.name }}"
    installcfg_master_servergrouppolicy: "{{ openshift_topology.servergroups.master | default('') }}"
    installcfg_ctrl_rootvolume: "{{ openshift_topology.controlplane_rootvolume | default({}) }}"
    installcfg_master_replicas: "{{ openshift_topology.replicas.master }}"
    installcfg_cidr: "{{ openshift_topology.openstack_infra[openshift_topology.network_primary].subnet.cidr }}"
    installcfg_network_type: "{{ openshift_topology.network_type }}"
    installcfg_external_network: "{{ openshift_topology.openstack_infra.external_network }}"
    installcfg_region: "{{ openshift_topology.openstack_infra.region }}"
    installcfg_dns_servers: "{{ openshift_topology.openstack_infra[openshift_topology.network_primary].subnet.dns_serverss }}"
    installcfg_api_floating_ip: "{{ precreated_api_fip }}"
    installcfg_ingress_floating_ip: "{{ precreated_ingress_fip }}"
