---
- name: Generate install-config.yaml from install-config-ipi.yaml.j2 template
  ansible.builtin.template:
    src: install-config-ipi.yaml.j2
    dest: "{{ user_cloud_installation_dir }}/install-config.yaml"
    mode: u=rw,g=rw,o=r
  vars:
    installcfg_ocp_base_domain: "{{ ocp_base_domain }}"
    installcfg_cluster_name: "{{ ocp_cluster_name }}"
    installcfg_worker_flavor: "{{ ocp_deployment_topology.flavors.worker.name }}"
    installcfg_worker_servergrouppolicy: "{{ ocp_deployment_topology.servergroups.worker | default('') }}"
    installcfg_worker_replicas: "{{ ocp_deployment_topology.replicas.worker }}"
    installcfg_master_flavor: "{{ ocp_deployment_topology.flavors.master.name }}"
    installcfg_master_servergrouppolicy: "{{ ocp_deployment_topology.servergroups.master | default('') }}"
    installcfg_ctrl_rootvolume: "{{ ocp_deployment_topology.controlplane_rootvolume | default(omit) }}"
    installcfg_master_replicas: "{{ ocp_deployment_topology.replicas.master }}"
    installcfg_subnet: "{{ ocp_deployment_topology[ocp_deployment_topology.primary_ip_protocol].tenant_subnet }}"
    installcfg_network_type: "{{ ocp_deployment_topology.network_type }}"
    installcfg_external_network: "{{ openstack_infra.external_network }}"
    installcfg_region: "{{ openstack_infra.region }}"
    installcfg_dns_servers: "{{ openstack_infra.network_config[ocp_deployment_topology.primary_ip_protocol].dns_servers }}"
    installcfg_api_vips: "{{ ocp_deployment_topology.primary_ip_protocol == 'ipv6' }}"
    installcfg_api_floating_ip: "{{ precreated_api_fip }}"
    installcfg_ingress_floating_ip: "{{ precreated_ingress_fip }}"
    installcfg_cluster_network: "{{ ocp_deployment_topology[ocp_deployment_topology.primary_ip_protocol].cluster_network }}"
    installcfg_service_network: "{{ ocp_deployment_topology[ocp_deployment_topology.primary_ip_protocol].service_network }}"
