---
- name: Generate install-config.yaml from install-config-ipi.yaml.j2 template
  ansible.builtin.template:
    src: install-config-ipi.yaml.j2
    dest: "{{ user_cloud_installation_dir }}/install-config.yaml"
    mode: u=rw,g=rw,o=r
  vars:
    installcfg_ocp_base_domain: "{{ ocp_base_domain }}"
    installcfg_cluster_name: "{{ ocp_cluster_name }}"
    installcfg_worker_flavor: "{{ topology.flavors.worker.name }}"
    installcfg_worker_servergrouppolicy: "{{ topology.servergroups.worker | default('') }}"
    installcfg_worker_replicas: "{{ topology.replicas.worker }}"
    installcfg_master_flavor: "{{ topology.flavors.master.name }}"
    installcfg_master_servergrouppolicy: "{{ topology.servergroups.master | default('') }}"
    installcfg_ctrl_rootvolume: "{{ topology.controlplane_rootvolume | default({}) }}"
    installcfg_master_replicas: "{{ topology.replicas.master }}"
    installcfg_machine_cidr: "{{ topology.machine_cidr }}"
    installcfg_network_type: "{{ openshift_network_type }}"
    installcfg_external_network: "{{ infra.external_network }}"
    installcfg_region: "{{ infra.region }}"
    installcfg_dns_servers: "{{ infra.dns_servers }}"
    installcfg_api_floating_ip: "{{ precreated_api_fip }}"
    installcfg_ingress_floating_ip: "{{ precreated_ingress_fip }}"
