---
- name: Include vars from registered resources
  ansible.builtin.include_vars:
    file: "{{ resources_file }}"
    name: resources

- name: Generate install-config.yaml from install-config-proxy.yaml.j2 template
  ansible.builtin.template:
    src: install-config-proxy.yaml.j2
    dest: "{{ user_cloud_installation_dir }}/install-config.yaml"
    mode: u=rw,g=rw,o=r
  vars:
    installcfg_ocp_base_domain: "{{ ocp_base_domain }}"
    installcfg_cluster_name: "{{ ocp_cluster_name }}"
    installcfg_worker_flavor: "{{ ocp_deployment_topology.flavors.worker.name }}"
    installcfg_worker_replicas: "{{ ocp_deployment_topology.replicas.worker }}"
    installcfg_master_flavor: "{{ ocp_deployment_topology.flavors.master.name }}"
    installcfg_master_replicas: "{{ ocp_deployment_topology.replicas.master }}"
    installcfg_machine_cidr: "{{ resources.restricted_cidr }}"
    installcfg_network_type: "{{ ocp_deployment_topology.network_type }}"
    installcfg_region: "{{ infra.region }}"
    installcfg_machines_subnet: "{{ resources.machines_subnet }}"
    installcfg_api_vip: "{{ precreated_api_fip }}"
    installcfg_ingress_vip: "{{ precreated_ingress_fip }}"
    installcfg_additional_trust_bundle: "{{ resources.additional_trust_bundle }}"
