---
- name: Make sure we are in the default project
  ansible.builtin.shell: |
    oc project default
  changed_when: true
  ignore_errors: true

- name: Merge all tests results into one XML file
  ansible.builtin.shell: |
    source /tmp/junit_venv/bin/activate
    junit2html {{ ansible_user_dir }}/{{ results_dir }}/junit_e2e_*.xml --merge={{ ansible_user_dir }}/{{ results_dir }}/tmp.xml
    deactivate
  changed_when: true

- name: Remove tests that are not {{ test_name }} from {{ test_name }}.xml
  ansible.builtin.script: |
    ../scripts/modifyE2ETags.py {{ results_dir }}/tmp.xml {{ results_dir }}/{{ test_name }}.xml {{ key_for_filtering_results }} {{ testsuite_name }} \
    > {{ ansible_user_dir }}/{{ results_dir }}/report_processing.log

- name: Convert test results to html inside virtualenv
  ansible.builtin.shell: |
    source /tmp/junit_venv/bin/activate
    junit2html {{ ansible_user_dir }}/{{ results_dir }}/{{ test_name }}.xml {{ ansible_user_dir }}/{{ results_dir }}/{{ test_name }}.html
    deactivate
  changed_when: true
