---
- name: Install GO
  ansible.builtin.include_tasks: install_go.yml

- name: Clone openshift/{{ repo_name }} repository
  ansible.builtin.git:
    repo: "https://github.com/openshift/{{ repo_name }}.git"
    version: release-{{ discovered_openshift_release }}
    dest: "{{ artifacts_dir }}/{{ repo_name }}"
    force: yes
    depth: 1
  retries: 3
  delay: 5
  register: openshift_repo
  until: openshift_repo is succeeded

- name: Remove the tests results directory ({{ results_dir }}) if it exists
  when: reset_result_dir | default(True)
  ansible.builtin.file:
    path: "{{ results_dir }}"
    state: absent

- name: Create a directory for the test results ({{ results_dir }})
  ansible.builtin.file:
    path: "{{ results_dir }}"
    state: directory
    mode: u=rwx,g=rw,o=r
