---
# DNS resolution management needed for RHOSO pods to be able to resolve
# shift-on-stack cluster Apps endpoints (for telemetry tests the RHOSO
# pods need to scrape metrics from shift-on-stack cluster prometheus
# federation route).
# It requires SSH passwordless login to the hypervisor
# (rhos-dfg-osasinfra-qe.pub in the hypervisor root user's
# authorized_keys, injected by satellite).
# https://issues.redhat.com/browse/SOSQE-2170
- name: Make sure there are no DNS entries for the domain '{{ ocp_base_domain }}'
  ansible.builtin.lineinfile:
    path: "{{ hypervisor_dnsmasq_addresses_file }}"
    regexp: "{{ ocp_base_domain }}"
    state: absent
  delegate_to: "{{ hypervisor }}"
  remote_user: root

- name: Include vars from registered resources
  ansible.builtin.include_vars:
    file: "{{ resources_file }}"
    name: resources

- name: Add the APPS DNS entry to the dnsmasq service in the hypervisor '{{ hypervisor }}'
  ansible.builtin.lineinfile:
    path: "{{ hypervisor_dnsmasq_addresses_file }}"
    line: "address=/apps.{{ ocp_cluster_name }}.{{ ocp_base_domain }}/{{ resources.apps_accessible_ip }}"
    insertafter: EOF  # Ensures the line is added at the end of the file
  delegate_to: "{{ hypervisor }}"
  remote_user: root

- name: Restart service in the hypervisor '{{ hypervisor_dnsmasq_service }}' - '{{ hypervisor }}'
  ansible.builtin.systemd:
    name: "{{ hypervisor_dnsmasq_service }}"
    state: restarted
  delegate_to: "{{ hypervisor }}"
  remote_user: root
