---
- name: Install custom cataloge source
  ansible.builtin.include_tasks: custom_catalog.yml
  when: use_custom_catalog_source

- name: Install NFD operator
  ansible.builtin.include_tasks: nfd.yml

- name: Install NVIDIA GPU operator
  ansible.builtin.include_tasks: gpu_operator.yml
