---
- name: Get the RHCOS image and upload it to Openstack
  ansible.builtin.include_tasks: prepare_rhcos_image.yml

- name: Create the Kubernetes manifests
  ansible.builtin.include_tasks: create_ocp_manifests.yml

- name: Create the Ignition config files
  ansible.builtin.include_tasks: ignition_configs.yml

- name: Retrieve the ansible playbooks for resource provisioning/deprovisioning
  ansible.builtin.include_tasks: retrieve_playbooks.yml

- name: Create the bootstrap ignition file and image
  ansible.builtin.include_tasks: bootstrap.yml

- name: Create the masters ignition files
  ansible.builtin.include_tasks: control_plane.yml

- name: Deploy the cluster
  ansible.builtin.include_tasks: deploy_cluster.yml
