---
- debug:
    msg : "{{ previous_installation_type }}"

- name: Destroy IPI cluster
  ansible.builtin.include_tasks: destroy_ipi.yml
  when: previous_installation_type == 'ipi'

- block:
    - name: Destroy UPI cluster
      include_tasks: destroy_upi.yml
  when: previous_installation_type == 'upi'
  delegate_to: "{{ installer_vm_name }}"

# - name: Destroy restricted cluster
#   include_tasks: destroy_restricted.yml
#   when: previous_installation_type == 'restricted'
