---
- name: Check if OCP cluster directory exists
  ansible.builtin.stat:
    path: "{{ ocp_installation_dir }}"
  register: ocp_cluster_directory

- name: Destroy OCP Cluster (IPI)
  when: ocp_cluster_directory.stat.exists
  block:
    # To-Do: https://issues.redhat.com/browse/OSPRH-7508
    - name: Run 'openshift-install destroy cluster'
      ansible.builtin.command: "openshift-install --log-level=debug destroy cluster --dir {{ ocp_installation_dir }}"
      async: 2400 # Timeout after 40 minutes
      poll: 60 # Check status every minute
      failed_when: false
      changed_when: true
      register: destroy_result

    - name: Fail if the openshift-install destroy cluster command did not succeed
      ansible.builtin.fail:
        msg: "Destroy OpenShift Cluster failed or timed out"
      when: destroy_result is failed
