---
- name: Destroy IPI cluster
  ansible.builtin.import_tasks: destroy_ipi.yml
  when: existing_ocp_installation_type == 'ipi'

- name: Destroy IPI Proxy (restricted) cluster
  vars:
    home_dir: "~"
  ansible.builtin.import_tasks: destroy_ipi.yml
  delegate_to: "{{ installer_vm_name }}"
  when: existing_ocp_installation_type == 'restricted'

- name: Destroy UPI cluster
  vars:
    home_dir: "~"
    upi_playbooks_logs_dir: "{{ upi_playbooks_dir }}/playbooks_logs"
    upi_inventory_file: "{{ upi_playbooks_dir }}/inventory.yaml"
  ansible.builtin.import_tasks: destroy_upi.yml
  delegate_to: "{{ installer_vm_name }}"
  when: existing_ocp_installation_type == 'upi'

- name: Remove API and APPS fip/vip from the /etc/hosts file
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ ocp_cluster_name }}"
    unsafe_writes: true
    state: absent
