---
- name: Destroy IPI cluster
  ansible.builtin.include_tasks: destroy_ipi.yml
  when: previous_installation_type == 'ipi'

# Uncomment this when https://issues.redhat.com/browse/OSPRH-6756 is done
# - name: Destroy UPI cluster
#   include_tasks: destroy_upi.yml
#   when: previous_installation_type == 'upi'
