---
- name: Ensure openshift-install binary is present
  block:
    - name: Check if openshift-install is present
      ansible.builtin.command: which openshift-install
      register: binary_check
      failed_when: false

    - name: Download openshift-install binary
      ansible.builtin.get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz"
        dest: "/tmp/openshift-install.tar.gz"
      when: binary_check.rc != 0

    - name: Extract openshift-install binary
      ansible.builtin.unarchive:
        src: "/tmp/openshift-install.tar.gz"
        dest: "/usr/local/bin"
        remote_src: yes
        extra_opts: [--strip-components=1]
      when: binary_check.rc != 0

- name: Check if OCP cluster directory exists
  ansible.builtin.stat:
    path: "{{ installation_dir }}"
  register: cluster_directory

- name: Destroy OCP Cluster (IPI)
  when: cluster_directory.stat.exists
  block:
    - name: Run 'openshift-install destroy cluster'
      ansible.builtin.command: "openshift-install --log-level=debug destroy cluster --dir {{ installation_dir }}"
      async: 2400 # Timeout after 40 minutes
      poll: 60 # Check status every minute
      failed_when: false
      changed_when: true
      register: destroy_result

    - name: Fail the play if the previous command did not succeed
      ansible.builtin.fail:
        msg: "Destroy OCP Cluster failed or timed out"
      when:
        - destroy_result is failed
