---
- name: Destroy OCP Cluster by running 'openshift-install destroy cluster'
  ansible.builtin.shell: |
      {{ ocp_installation_dir }}/openshift-install destroy cluster --log-level debug --dir {{ ocp_installation_dir }}
  environment:
    OS_CLOUD: "{{ user_cloud }}"
  changed_when: true
  async: 3600 # Timeout after one hour
  poll: 60 # Check status every minute
  register: destroy_result
  failed_when:
    - destroy_result is failed
    - not force_cleanup

- name: Mark as UNSTABLE if the cluster destroy failed and force_cleanup is enabled
  ansible.builtin.include_role:
    name: tools_stage_results
    tasks_from: mark_stage_unstable.yml
  vars:
    unstable_msg: >-
      Cluster destroy failed. Ignoring as force_cleanup is enabled.
  when:
    - destroy_result is failed
    - force_cleanup

- name: Remove the OCP cluster directory
  ansible.builtin.file:
    path: "{{ ocp_installation_dir }}"
    state: absent
