---
- name: Destroy IPI cluster
  ansible.builtin.include_tasks: destroy_ipi.yml
  when: previous_installation_type == 'ipi'

- name: Destroy UPI cluster on installer host
  when: previous_installation_type == 'upi'
  block:
    - name: Destroy UPI cluster
      vars:
        home_dir: "/home/{{ installer_vm_ssh_user }}"
        upi_playbooks_logs_dir: "{{ artifacts_dir }}/playbooks_logs"
      include_tasks: destroy_upi.yml
  delegate_to: "{{ installer_vm_name }}"

# TO-DO: Add restricted cluster cleanup
# - name: Destroy restricted cluster
#   include_tasks: destroy_restricted.yml
#   when: previous_installation_type == 'restricted'
