---
- name: Check if OCP cluster directory exists
  ansible.builtin.stat:
    path: "{{ installation_dir }}"
  register: cluster_directory

- name: Destroy OCP Cluster (IPI)
  block:
    - name: Run 'openshift-install destroy cluster'
      command: "openshift-install --log-level=debug destroy cluster --dir {{ installation_dir }}"
      async: 2400 # Timeout after 40 minutes
      poll: 60 # Check status every minute
      failed_when: false
      register: destroy_result

    - name: fail the play if the previous command did not succeed
      fail:
        msg: "Destroy OCP Cluster failed or timed out"
      when:
        - destroy_result is failed
  when: cluster_directory.stat.exists