---
- name: Detect environment specifics
  ansible.builtin.include_tasks: detect_env.yml

- name: Destroy clusters based on type
  ansible.builtin.include_tasks: destroy_clusters.yml

- name: Cleanup OpenStack Resources
  ansible.builtin.include_tasks: openstack_cleanup.yml
