---
- name: Check if OpenStack "{{ user_cloud }}" project exists
  openstack.cloud.project_info:
    cloud: "{{ admin_cloud }}"
    name: "{{ user_cloud }}"
    verify: "{{ admin_verify_cacert }}"
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ osp_config_dir }}/clouds.yml"
  register: openstack_project_info
  ignore_errors: true # noqa: ignore-errors

- name: Notify that the OpenStack cloud doesn't exist
  ansible.builtin.debug:
    msg: |
      OpenStack cloud does not exist: "{{ admin_cloud }}"
  when: openstack_project_info is failed

- name: Cleanup the OpenStack project in the case the OpenStack cloud exists
  when: openstack_project_info is succeeded
  block:
    - name: Fail if more than one OpenStack "{{ user_cloud }}" project exist
      when: openstack_project_info.projects | length > 1
      ansible.builtin.fail:
        msg: >-
          Cleanup failed.
          More than one OpenStack "{{ user_cloud }}" project: {{ openstack_project_info.projects | length }}

    - name: Cleanup the ShiftStack setup
      when: openstack_project_info.projects | length == 1
      block:
        - name: Restore installation dir
          ansible.builtin.copy:
            src: "{{ osp_config_dir }}"
            dest: "{{ home_dir }}/.config/openstack/"
            mode: u=rwx,g=rwx,o=rwx
            remote_src: yes

        - name: Discover the OpenShift installation type
          ansible.builtin.include_tasks: detect_ocp_installation.yml

        - name: Destroy the OpenShift cluster if it exists
          ansible.builtin.include_tasks: destroy_openshift_cluster.yml
          when: existing_ocp_installation_type != ''

        - name: Cleanup the OpenStack project
          vars:
            project: "{{ openstack_project_info.projects[0] }}"
          ansible.builtin.include_tasks: openstack_project_cleanup.yml
