---
- name: Check if OpenStack "{{ user_cloud }}" project exists
  openstack.cloud.project_info:
    cloud: "{{ admin_cloud }}"
    name: "{{ user_cloud }}"
  register: openstack_project_info

- name: Cleanup the ShiftStack setup
  when: openstack_project_info.projects | length > 0
  block:
    - name: Discover the OpenShift installation type
      ansible.builtin.include_tasks: detect_ocp_installation.yml

    - name: Destroy the OpenShift cluster if it exists
      ansible.builtin.include_tasks: destroy_openshift_cluster.yml
      when: existing_ocp_installation_type != ''

    - name: Cleanup the OpenStack project
      vars:
        project: "{{ openstack_project_info.projects[0] }}"
      ansible.builtin.include_tasks: openstack_project_cleanup.yml
