---
- name: Add RH-IT-Root-CA.crt certificate
  ansible.builtin.get_url:
    url: "{{ redhat_ca_file }}"
    dest: /etc/pki/ca-trust/source/anchors/custom-ssl-ca.crt
    validate_certs: no
    mode: u=rw,g=rw,o=r
  become: true
  register: custom_ca

- name: Update system trust store
  when: custom_ca is changed
  ansible.builtin.command: update-ca-trust
  changed_when: true # noqa: no-handler
  become: true

- name: Install required packages in the installer host
  ansible.builtin.package:
    name: "{{ installer_required_packages }}"
    state: present
  register: result
  become: true
  retries: 10
  delay: 10
  until: not result.failed

- name: Install Python packages via pip in the installer host
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  become: yes
  loop: "{{ installer_python_packages }}"

- name: Install ansible and ansible collections for UPI
  when: installation_type == 'upi'
  block:
    - name: Install ansible-core for running UPI playbooks in the installer host
      ansible.builtin.package:
        name:
          - 'ansible-core'
        state: present
      register: result
      become: true
      retries: 10
      delay: 10
      until: not result.failed

    - name: Install required ansible collections for UPI mode in the installer host
      ansible.builtin.command: "ansible-galaxy collection install {{ item }} --force-with-deps -vvv"
      loop: "{{ installer_upi_ansible_collections }}"
      changed_when: true
      register: result
      retries: 10
      delay: 10
      until: not result.failed

- name: Ensure that the python command points to python3
  when: installation_type == 'upi'
  block:
    - name: Check if Python command points to Python 3
      ansible.builtin.command: "python --version"
      changed_when: false
      failed_when: false
      register: python_version_output

    - name: Set python3 as default if symlink doesn't exist or doesn't point to python3
      ansible.builtin.shell: |
        alternatives --set python /usr/bin/python3
      changed_when: true
      become: true
      when: "'Python 3' not in python_version_output.stdout"
