---
- name: Include vars from registered resources
  ansible.builtin.include_vars:
    file: "{{ resources_file }}"
    name: resources

- name: Add API and APPS floating IPs to /etc/hosts file
  vars:
    api_fip: "{{ resources.api_fip }}"
    apps_fip: "{{ resources.apps_fip }}"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ item.regex }}"
    line: "{{ item.row }}"
  loop: "{{ etc_hosts_entries }}"
