---
- name: Make sure chronyd is installed
  become: yes
  ansible.builtin.package:
    name: chrony
    state: latest

- name: Deploy chrony.conf template
  become: yes
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=rwx
    backup: yes

- name: Restart chronyd
  become: yes
  ansible.builtin.service:
    name: chronyd
    state: restarted

- name: Add rules to the security group {{ installer_vm.sec_group.name }}
  openstack.cloud.security_group_rule:
    cloud: "{{ user_cloud }}"
    security_group: "{{ installer_vm.sec_group.name }}"
    direction: "{{ item.direction }}"
    ethertype: "{{ item.ethertype }}"
    remote_ip_prefix: "{{ item.remote_ip_prefix }}"
    protocol: "{{ item.protocol | default(omit) }}"
    port_range_min: "{{ item.port_range_min | default(omit) }}"
    port_range_max: "{{ item.port_range_max | default(omit) }}"
  with_items: "{{ installer_vm.ntp.sg_rules }}"
