---
- name: Provision the installer host VM
  ansible.builtin.include_tasks: provision.yml

- name: Create the installer group (and add a host) in the inventory
  ansible.builtin.include_tasks: add_installer_host_to_installer_group.yml
  vars:
    installer_host_fip: "{{ installer_vm_fip.stdout }}"

- name: Copy workspace files from the undercloud to the installer VM
  ansible.builtin.import_tasks: configuration_copy_workspace.yml
  delegate_to: "{{ installer_vm_name }}"

- name: Add entries to /etc/hosts file in the installer VM
  ansible.builtin.import_tasks: configuration_hosts.yml
  delegate_to: "{{ installer_vm_name }}"

- name: Install repos in the installer VM
  ansible.builtin.import_tasks: configuration_install_repos.yml
  delegate_to: "{{ installer_vm_name }}"

- name: Install packages in the installer VM
  ansible.builtin.import_tasks: configuration_install_packages.yml
  delegate_to: "{{ installer_vm_name }}"

- name: Configure the installer VM for OpenShift proxy installation
  when: openshift_proxy_installation
  block:
    - name: Configure squid on the installer vm
      ansible.builtin.import_tasks: install_squid.yml
      delegate_to: "{{ installer_vm_name }}"

    - name: Install and configure dnsmasq on the installer host
      ansible.builtin.import_tasks: install_dnsmasq.yml
      delegate_to: "{{ installer_vm_name }}"

    - name: Install NTP server on the installer host
      ansible.builtin.import_tasks: install_chronyd.yml
      delegate_to: "{{ installer_vm_name }}"
