---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 98-var-lib-etcd
spec:
  config:
    ignition:
      version: 3.4.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Mount local-etcd to /var/lib/etcd
            [Mount]
            What=/dev/disk/by-label/local-etcd
            Where=/var/lib/etcd
            Type=xfs
            Options=defaults,prjquota
            [Install]
            WantedBy=local-fs.target
          enabled: true
          name: var-lib-etcd.mount
        - contents: |
            [Unit]
            Description=Create local-etcd filesystem
            DefaultDependencies=no
            After=local-fs-pre.target
            ConditionPathIsSymbolicLink=!/dev/disk/by-label/local-etcd
            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=/bin/bash -c "[ -L /dev/disk/by-label/ephemeral0 ] || ( >&2 echo Ephemeral disk does not exist; /usr/bin/false )"
            ExecStart=/usr/sbin/mkfs.xfs -f -L local-etcd /dev/disk/by-label/ephemeral0
            [Install]
            RequiredBy=dev-disk-by\x2dlabel-local\x2detcd.device
          enabled: true
          name: create-local-etcd.service
        - contents: |
            [Unit]
            Description=Migrate existing data to local etcd
            After=var-lib-etcd.mount
            Before=crio.service
            Requisite=var-lib-etcd.mount
            ConditionPathExists=!/var/lib/etcd/member
            ConditionPathIsDirectory=/sysroot/ostree/deploy/rhcos/var/lib/etcd/member
            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=/bin/bash -c "if [ -d /var/lib/etcd/member.migrate ]; then rm -rf /var/lib/etcd/member.migrate; fi"
            ExecStart=/usr/bin/cp -aZ /sysroot/ostree/deploy/rhcos/var/lib/etcd/member/ /var/lib/etcd/member.migrate
            ExecStart=/usr/bin/mv /var/lib/etcd/member.migrate /var/lib/etcd/member
            [Install]
            RequiredBy=var-lib-etcd.mount
          enabled: true
          name: migrate-to-local-etcd.service
        - contents: |
            [Unit]
            Description=Relabel /var/lib/etcd
            After=migrate-to-local-etcd.service
            Before=crio.service
            Requisite=var-lib-etcd.mount
            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecCondition=/bin/bash -c "[ -n \"$(restorecon -nv /var/lib/etcd)\" ]"
            ExecStart=/usr/sbin/restorecon -R /var/lib/etcd
            [Install]
            RequiredBy=var-lib-etcd.mount
          enabled: true
          name: relabel-var-lib-etcd.service
