---
# MachineConfigPool for SRIOV worker nodes
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: sriov
  labels:
    machineconfiguration.openshift.io/role: sriov
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values: [sriov, worker]
  paused: false
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/sriov: ""

---
# MachineConfigPool for DPDK worker nodes
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: dpdk
  labels:
    machineconfiguration.openshift.io/role: dpdk
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values: [dpdk, worker]
  paused: false
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/dpdk: ""
