---
# Sets the Ansible Target (a.k.a Managed Node) HOME environment variable to its actual value
# This ensures scripts and applications running on the target machine know the user's home directory
# artifacts/
# ├── installation
# │   └── shiftstack                   # Dedicated dir for OSP user_cloud - `user_cloud_installation_dir`
# │       ├── install-config.yaml
# │       ├── openstack                # OSP config dir - `osp_config_dir`
# │       │   ├── clouds.yaml
# │       │   └── shiftstackrc
# │       └── ostest                   # OCP cluster installation dir - `ocp_installation_dir`
#
# Note: The ci-framework job overwriting the 'user_cloud' and 'ocp_cluster_name'.
#       Reference: https://github.com/openstack-k8s-operators/ci-framework/pull/1882
cacert: "{{ home_dir }}/.original-config/cert/ca.crt"
home_dir: "{{ ansible_facts.env['HOME'] }}"
artifacts_dir: "{{ home_dir }}/artifacts"
installation_dir: "{{ artifacts_dir }}/installation"
installer_host_cacert: "/etc/pki/ca-trust/source/anchors/ca.crt"
legacy_installation: false
user_cloud: "shiftstack"
ocp_base_domain: "{{ user_cloud }}.local"
user_cloud_installation_dir: "{{ installation_dir }}/{{ user_cloud }}"
osp_config_dir: "{{ user_cloud_installation_dir }}/openstack"
ocp_cluster_name: "ostest"
ocp_installation_dir: "{{ user_cloud_installation_dir }}/{{ ocp_cluster_name }}"
kubeconfig: "{{ ocp_installation_dir }}/auth/kubeconfig"
upi_playbooks_dir: "{{ ocp_installation_dir }}"
report_dir: "{{ artifacts_dir }}/test_results"

# Sets the Ansible Controller Node machine's HOME environment variable
controller_home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
# The resources_file and stage_unstable_flag are in the Ansible control node's HOME environment variable
resources_file: "{{ controller_home_dir }}/artifacts/resources.yml"
stage_unstable_flag: "{{ controller_home_dir }}/artifacts/stage_unstable_flag"

admin_cloud: "default"
admin_env_file: "{{ osp_config_dir }}/{{ admin_cloud }}rc"
admin_verify_cacert: false
user_env_file: "{{ osp_config_dir }}/{{ user_cloud }}rc"
clouds_yaml_file_path: "{{ home_dir }}/.config/openstack/clouds.yaml"
secure_yaml_file_path: "{{ home_dir }}/.config/openstack/secure.yaml"

openstack_infra: # The required OpenStack deployment info for deploying OCP on the OSP infra
  external_network: public
  region: regionOne
  network_config:
    ipv4:
      dns_servers:
        - '192.168.122.1' # This is the gateway IP of the external network
    ipv6:
      dns_servers:
        - '2620:cf:cf:aaaa::1' # This is the gateway IP of the external network

ocp_deployment_topology: # The deployment info for deploying OCP on the OSP infra
  network_type: OVNKubernetes  # SDN type used for the deployment
  primary_ip_protocol: ipv4    # Primary IP version stack (ipv4 or ipv6)
  secondary_ip_protocol: ""    # Optional secondary IP stack for dual-stack (e.g., ipv4, ipv6, or "" for single-stack)
  ipv4:
    ip_version: 4
    tenant_subnet:
      cidr: 10.196.0.0/16     # CIDR for the machine network (tenant network)
  ipv6:
    ip_version: 6
    tenant_network:
      name: network-ssipv6
    tenant_subnet:
      name: subnet-ssipv6
      # https://gitlab.cee.redhat.com/ci-framework/ci-framework-jobs/-/merge_requests/1200/diffs#4d73ff9305400214f604415957c2feea06cc2c65_0_164
      cidr: fd2e:6f44:5dd8:c956::/64 # CIDR for the machine network (tenant network)
      ra_mode: dhcpv6-stateful # Only mode supported in 4.18
      addr_mode: dhcpv6-stateful # Only mode supported in 4.18
    ocp_api_port:
      name: api-ssipv6
      ip_address: fd2e:6f44:5dd8:c956::5
    ingress_api_port:
      name: ingress-ssipv6
      ip_address: fd2e:6f44:5dd8:c956::7
    tenant_router:
      name: router-ssipv6
    gateway: 2620:cf:cf:aaaa:ffff:ffff:ffff:111 # https://gitlab.cee.redhat.com/ci-framework/ci-framework-jobs/-/merge_requests/1200/diffs#4d73ff9305400214f604415957c2feea06cc2c65_0_166
  replicas:
    master: 3
    worker: 3
  flavors:
    master:
      name: "master"
      ram: 16384
      vcpus: 4
      disk: 100
    worker:
      name: "worker"
      ram: 8192
      vcpus: 2
      disk: 100
    bootstrap:
      name: "bootstrap"
      ram: 16384
      vcpus: 4
      disk: 100

wait_retries: 30
wait_delay: 30
manifests_wait_timeout: 300

openstack_ssl: true
openstack_tlse: false
openstack_key_file: "{{ home_dir }}/.ssh/rhos-dfg-osasinfra-qe"
redhat_ca_file: "https://certs.corp.redhat.com/RH-IT-Root-CA.crt"

openshift_proxy_installation: false
openshift_manila_type: "foo"
openshift_mirror: false

deploy_installer_host: false
installer_vm_ssh_user: "cloud-user"
custom_network: ''
custom_subnet: ''
custom_router: ''
custom_ports: []
custom_flavor: ''
installer_vm_name: "installer-host"
installer_group: "installer"
installer_ansible_python_interpreter: '/usr/libexec/platform-python'
installer_network: "{{ installer_vm_name | default('installer_host-network', true) }}"
installer_subnet: "{{ custom_subnet | default('installer_host-subnet', true) }}"
installer_router: "{{ custom_router | default('installer_host-router', true) }}"
installer_flavor_name: "{{ custom_flavor| default('m1.medium', true) }}"

restricted_network:
  network_name: 'restricted_network'
  subnet_name: 'restricted_subnet'
  installer_port_name: 'installer_restricted_network_port'
  cidr: '172.16.0.0/24'
  pool_start: '172.16.0.8'
  pool_end: '172.16.0.254'
  installer_ip: '172.16.0.3'
  default_gw: '172.16.0.1' # Used with OpenshiftSDN networking type
  ocp_api_ip: '172.16.0.5'
  ocp_apps_ip: '172.16.0.7'

inventory:
  dir: "/etc/ansible"
  hosts_file: "{{ artifacts_dir }}/hosts-installer"
  backup_file: "{{ artifacts_dir }}/hosts-installer.bck"

upi_playbooks_logs_dir: "{{ upi_playbooks_dir }}/playbooks_logs"

tests:
  default_go_version_target: '1.22.5'
