---
admin_cloud: "overcloud"
cacert: "/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem"
cacert_tlse: "/etc/pki/ca-trust/source/anchors/ca.crt"
legacy_installation: true
openstack_infra: # Store required Openstack deployment info for deploying OCP
  external_network: public
  region: regionOne
  dns_servers:
    - '10.47.242.10'
