---
cacert: "/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem"
cacert_tlse: "/etc/pki/ca-trust/source/anchors/ca.crt"
legacy_installation: true
infra: # Store required Openstack deployment info for deploying OCP
  external_network: nova
  region: regionOne
  dns_servers:
    - '10.47.242.10'
