---
admin_cloud: default
cacert: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
infra: # Store required Openstack deployment info for deploying OCP
  external_network: public
  region: regionOne
  dns_servers:
    - '10.47.242.10'
