---
admin_cloud: default
user_cloud: shiftstack
cacert: "{{ home_dir }}/.original-config/cert/ca.crt"
ocp_cluster_name: ostest
topology: # Store required params for deploying OCP
  flavors:
    master:
      name: master
      ram: 16384
      vcpus: 4
      disk: 100 # openshift-qe-xxx setups require disk: 10
    worker:
      name: worker
      ram: 8192
      vcpus: 2
      disk: 100 # openshift-qe-xxx setups require disk: 10
  replicas:
    master: 3
    worker: 3
  network_type: OVNKubernetes
  machine_cidr: 10.196.0.0/16
infra: # Store required Openstack deployment info for deploying OCP
  external_network: public
  region: regionOne
  dns_servers:
    - '10.47.242.10'
