---
admin_cloud: default
cacert: "{{ home_dir }}/.original-config/cert/ca.crt"
infra: # Store required Openstack deployment info for deploying OCP
  external_network: public
  region: regionOne
  dns_servers:
    - '10.47.242.10'
octavia_blocker_bugs_fixed: false # Amphora-Octavia is not working in RHOSP18 until OSPRH-387 and OSPRH-399 are done
