---
admin_cloud: default
cacert: "~/.original-config/cert/ca.crt"
infra: # Store required Openstack deployment info for deploying OCP
  external_network: public
  region: regionOne
  dns_servers:
    - '10.47.242.10'
