---
- name: "'mark_stage_unstable' action"
  block:
    - name: Set the stage unstable var as true
      ansible.builtin.set_fact:
        stage_unstable: true
        unstable_warning: "Warning! {{ unstable_msg }}"

    - name: Print the stage UNSTABLE message
      ansible.builtin.debug:
        msg: "{{ unstable_warning }}"

    - name: Mark the stage result as UNSTABLE
      ansible.builtin.lineinfile:
        path: "{{ stage_unstable_flag }}"
        line: "{{ unstable_warning }}"
        create: yes
      delegate_to: localhost
