---
- name: Day2ops OpenShift stage
  hosts: installer
  gather_facts: no
  vars_files:
    - "../../configs/global.yml"
  tasks:
    - name: Main block
      block:
        - name: Run day2 operations on OCP
          ansible.builtin.include_role:
            name: shiftstack.stages.day2ops
          vars:
            day2ops_steps: "{{ day2ops_procedures }}"

      rescue:
        - name: Check if source directory exists
          ansible.builtin.stat:
            path: "{{ artifacts_dir }}"
          register: source_dir_stat

        - name: Synchronize artifacts from the Ansible Managed Node to Ansible Controller
          ansible.posix.synchronize:
            src: "{{ artifacts_dir }}"
            dest: "{{ controller_home_dir }}"
            mode: pull
            recursive: yes
            times: false
            perms: false
          when: source_dir_stat.stat.exists
