---
- name: Day2ops OpenShift stage
  hosts: installer
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/../configs/main_config.yaml"
  tasks:
    - name: Main block
      block:
        - name: Run day2 operations on OCP
          ansible.builtin.include_role:
            name: shiftstack.stages.day2ops
          vars:
            day2ops_steps: "{{ day2ops_procedures }}"
      always:
        - name: Synchronize artifacts from the Ansible Managed Node to Ansible Controller
          ansible.builtin.include_role:
            name: shiftstack.tools.tools_ansible
            tasks_from: sync_artifacts.yml
