---
- name: Install OpenShift new candidate on OSP
  hosts: installer
  gather_facts: no
  vars_files:
    - "../../configs/global.yml"
    - "../../configs/secret.yaml"
  tasks:
    - name: Install OCP on setup
      ansible.builtin.include_role:
        name: shiftstack.stages.install
