---
- name: Post OpenShift installation stage
  hosts: installer
  gather_facts: no
  vars_files:
    - "../../configs/global.yml"
  tasks:
    - name: Main block
      block:
        - name: Run post operations and OCP verification checks on setup
          ansible.builtin.include_role:
            name: shiftstack.stages.post
      always:
        - name: Synchronize artifacts from the Ansible Managed Node to Ansible Controller
          ansible.builtin.include_role:
            name: shiftstack.tools.tools_ansible_inventory
            tasks_from: sync_artifacts.yml
