---
- name: Upgrade OpenShift cluster
  hosts: installer
  gather_facts: no
  vars_files:
    - "../../configs/global.yml"
  tasks:
    - name: Main block
      block:
        - name: Run OCP upgrade
          ansible.builtin.include_role:
            name: shiftstack.stages.upgrade
      always:
        - name: Synchronize artifacts
          ansible.builtin.include_role:
            name: shiftstack.tools.tools_ansible_inventory
            tasks_from: sync_artifacts.yml
