---
- name: Obtain a list of procedures that user can run
  ansible.builtin.find:
    paths: "{{ role_path }}/tasks/procedures"
    recurse: no
    file_type: file
  register: find_output
  delegate_to: localhost

- name: Create list var of available procedures
  ansible.builtin.set_fact:
    day2ops_available_procedures: >
      {{
        find_output.files |
        map(attribute='path') |
        map('basename') |
        list
      }}

- name: Assert that there is at least one procedure to run
  ansible.builtin.assert:
    that:
      - day2ops_steps | length > 0
    fail_msg: |
      Day2ops role has been called without any procedure to run.
      Please set 'day2ops_steps' var list with at least one element
      from the following list (removing the .yml extension):
      {{ day2ops_available_procedures | to_nice_json }}

- name: Create report file if it does not exist
  ansible.builtin.file:
    path: "{{ report_dir }}"
    mode: u=rwx,g=rw,o=r
    state: directory

- name: Generate empty report file
  ansible.builtin.template:
    src: day2ops-report.xml.j2
    dest: "{{ report_dir }}/{{ day2ops_report_filename }}"
    mode: u=rw,g=rw,o=r

- name: Run day2ops procedures sequentially
  ansible.builtin.include_tasks: run_procedure.yml
  vars:
    procedure_task_file: "{{ item }}.yml"
  loop: "{{ day2ops_steps }}"
