---
- name: Assert that the day2ops procedure task file exists
  ansible.builtin.assert:
    that:
      - procedure_task_file in day2ops_available_procedures
    fail_msg: |
      The {{ procedure_task_file }} is not available inside this role.
      Please use one of the following by setting it inside the list var
      'day2ops_step' removing the extension '.yml':
      {{ day2ops_available_procedures | to_nice_json }}
    success_msg: |
      Running task file {{ procedure_task_file }}

- name: Run day2ops procedure {{ procedure_task_file }}
  vars:
    procedure: "{{ procedure_task_file | regex_replace('\\.yml$', '') }}"
    report_path: "{{ report_dir }}/{{ day2ops_report_filename }}"
  block:

    - name: Create entry on report
      community.general.xml:
        path: "{{ report_path }}"
        xpath: /day2ops/{{ procedure }}

    - name: Store start time on report for {{ procedure }}
      community.general.xml:
        path: "{{ report_path }}"
        xpath: /day2ops/{{ procedure }}
        attribute: start_time
        value: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}"

    - name: Run the day2ops procedure
      ansible.builtin.include_tasks: "procedures/{{ procedure_task_file }}"

    - name: Run verification after day2ops procedure
      ansible.builtin.include_role:
        name: shiftstack.stages.verification
      vars:
        skip_mustgather_generation: true

    - name: Write result:SUCCESS on report for {{ procedure }}
      community.general.xml:
        path: "{{ report_path }}"
        xpath: /day2ops/{{ procedure }}
        attribute: result
        value: PASSED

  rescue:
    - name: Write result:FAILED on report for {{ procedure }}
      community.general.xml:
        path: "{{ report_path }}"
        xpath: /day2ops/{{ procedure }}
        attribute: result
        value: FAILED

    - name: Write failed_task on report for {{ procedure }}
      community.general.xml:
        path: "{{ report_path }}"
        xpath: /day2ops/{{ procedure }}
        attribute: failed_task
        value: "{{ (ansible_failed_task is defined) | ternary(ansible_failed_task.name, 'UNKNOWN') }}"

    - name: Run must-gather
      ansible.builtin.include_role:
        name: tools_must-gather
      vars:
        must_gather_suffix: "{{ procedure_task_file | regex_replace('\\.yml$', '') }}"

    - name: Fail the playbook in a case of failure
      ansible.builtin.fail:
        msg: >
          Failed! See logs and must-gather for more information.
          The {{ procedure_task_file }} task file failed.

  always:
    - name: Write end_time on report for {{ procedure }}
      community.general.xml:
        path: "{{ report_dir }}/{{ day2ops_report_filename }}"
        xpath: /day2ops/{{ procedure_task_file | regex_replace('\\.yml$', '') }}
        attribute: end_time
        value: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}"
