---
# defaults file for openstack_test
openstack_test_name: openstack-test
openstack_test_dir: "{{ home_dir }}/{{ openstack_test_name }}"
openstack_test_results_dir: "{{ home_dir }}/{{ openstack_test_name }}-results"
openstack_tests_allowlist_file: ""
openstack_tests_blocklist_file: ""
openstack_tests_go_version: "1.20"
