---
- name: Create control plane ignition config files
  vars:
    script: |
      for index in $(seq 0 2); do
      MASTER_HOSTNAME="{{ ocp_infra_id }}-master-$index\n"
      python3 -c "import base64, json, sys
      ignition = json.load(sys.stdin)
      storage = ignition.get('storage', {})
      files = storage.get('files', [])
      files.append({'path': '/etc/hostname', 'mode': 420, 'contents': {'source': 'data:text/plain;charset=utf-8;base64,' + base64.standard_b64encode(b'$MASTER_HOSTNAME').decode().strip()}})
      storage['files'] = files
      ignition['storage'] = storage
      json.dump(ignition, sys.stdout)" <master.ign >"{{ ocp_infra_id }}-master-$index-ignition.json"
      done
  ansible.builtin.shell: "{{ script }}" # noqa: command-instead-of-shell
  changed_when: true
  args:
    chdir: "{{ ocp_installation_dir }}"
