---
- name: Check the project's instances healthy
  block:
    - name: Get information about the "{{ user_cloud }}" project servers
      openstack.cloud.server_info:
        cloud: "{{ user_cloud }}"
      register: project_servers

    - name: Fail if not all project servers are active
      vars:
        error_msg: >
          Failed! The {{ item.name }} server in the {{ user_cloud }} project
          is in {{ item.vm_state }} status.
      fail:
        msg: "{{ error_msg }}"
      when: item.vm_state != "active"
      loop: "{{ project_servers.openstack_servers }}"
  rescue:
    - name: Get Instances, Machines, and MachineSets information for unhealthy project instances
      include_tasks: debug_machines.yml

    - name: Fail inside rescue block
      fail:
        msg: "The OSP servers health check failed. See above commands output for more information."
