---
- name: Check MCP is updated
  block:
    - name: Wait 1 minute before checking nodes and MCP
      pause:
        minutes: 1

    - name: Wait for the machine config pool to finish the cluster updates
      shell: |
        oc wait --all --for=condition=Updated --timeout=1200s mcp
      retries: "{{ wait_retries }}"
      delay: "{{ wait_delay }}"
      register: result
      until: result.rc == 0
