---
- name: Configure hypervisor for making it available for Prow
  hosts: localhost
  gather_facts: yes
  vars_files:
    - "../configs/secret.yaml"

  tasks:
    - name: Install squid on the hypervisor
      vars:
        delegated_host: "{{ hypervisor }}"
        delegated_user: "root"
        squid_user: "{{ proxy_user }}"
        squid_password: "{{ proxy_password }}"
      ansible.builtin.include_role:
        name: shiftstack.tools.tools_install_squid

    - name: Create user and store the proxied kubeconfig in its home folder
      delegate_to: "{{ hypervisor }}"
      remote_user: "root"
      block:
        - name: Create a user with a home directory
          ansible.builtin.user:
            name: "{{ proxy_user }}"
            home: /home/{{ proxy_user }}
            shell: /bin/bash
            password: "{{ proxy_password | password_hash('sha512') }}"
            createhome: yes
            state: present

        - name: Copy incluster-kubeconfig from the shiftstackclient pod
          ansible.builtin.copy:
            src: ~/incluster-kubeconfig
            dest: /home/{{ proxy_user }}/kubeconfig
            owner: "{{ proxy_user }}"
            group: "{{ proxy_user }}"
            mode: '0600'

        - name: Get the IP address of an FQDN using dig
          ansible.builtin.shell: 'dig +short $(hostname)'
          register: fqdn_ip_result
          changed_when: false

        - name: Set IP address fact
          ansible.builtin.set_fact:
            hypervisor_ip_address: "{{ fqdn_ip_result.stdout.splitlines()[0] }}"

        - name: Add proxy-url after "server:" line in the kubeconfig
          ansible.builtin.replace:
            path: /home/{{ proxy_user }}/kubeconfig
            regexp: '^( *)(server:.*)$'
            replace: '\1\2\n\1proxy-url: http://{{ proxy_user }}:{{ proxy_password }}@{{ hypervisor_ip_address }}:3128'
          backup: yes

        - name: Confirm that underlying OCP cluster is healthy
          vars:
            kubeconfig: "/home/{{ proxy_user }}/kubeconfig"
          ansible.builtin.include_role:
            name: tools_cluster_checks
            tasks_from: wait_until_cluster_is_healthy.yml
        # TBD: Check that openstack is healthy too