---
- name: OCP testing for new candidate on legacy OSP (17.1 or 16.2)
  hosts: localhost
  gather_facts: no
  # debugger: on_failed # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_debugger.html#playbook-debugger
  vars_files:
    - "../configs/global.yml"
    - "../configs/secret.yaml"
    - "../configs/legacy_ocp_testing.yaml"

  environment:
    KUBECONFIG: "{{ kubeconfig }}"

  pre_tasks:
    - name: Preparing for the run
      ansible.builtin.debug:
        msg: "Preparing for the run..."

    - name: Gather host environment variables
      ansible.builtin.setup:
        gather_subset:
          - env

    - name: Cleanup workspace flags - Remove the stage_unstable_flag if it exists
      ansible.builtin.file:
        path: "{{ stage_unstable_flag }}"
        state: absent

  tasks:
    - name: Discover OSP version
      ansible.builtin.include_role:
        name: shiftstack.tools.tools_get_deploy_info
        tasks_from: discover_osp_version.yml

    - name: Cleanup setup
      ansible.builtin.include_role:
        name: shiftstack.stages.cleanup
      when: "'cleanup' in stages"

    - name: Prepare setup
      ansible.builtin.include_role:
        name: shiftstack.stages.prepare
      when: "'prepare' in stages"

    - name: Install OCP on setup
      ansible.builtin.include_role:
        name: shiftstack.stages.install
      when: "'install' in stages"

    - name: Discover OCP version and networkType
      ansible.builtin.include_role:
        name: shiftstack.tools.tools_get_deploy_info
        tasks_from: discover_ocp_version.yml

    - name: Run post operations and OCP verification checks on setup
      ansible.builtin.include_role:
        name: shiftstack.stages.post
      when: "'post' in stages"

    - name: Run OCP verification checks
      ansible.builtin.include_role:
        name: shiftstack.stages.verification
      vars:
        post_installatin: true
      when: "'verification' in stages"

    - name: Run Openstack-Test on OCP
      ansible.builtin.include_role:
        name: shiftstack.stages.openstack_test
      when: "'openstack_test' in stages"

    - name: Run day2ops
      ansible.builtin.include_role:
        name: shiftstack.stages.day2ops
      when: "'day2ops' in stages"

  post_tasks:
    - name: Gathering resources
      ansible.builtin.debug:
        msg: "Gathering resources..."
