---
- name: OCP testing for new candidate on legacy OSP (17.1 or 16.2)
  hosts: localhost
  gather_facts: no
  # debugger: on_failed # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_debugger.html#playbook-debugger
  vars_files:
    - "../configs/secret.yaml"
    - "../configs/legacy_ocp_testing.yaml"

  pre_tasks:
    - name: Preparing for the run
      ansible.builtin.debug:
        msg: "Preparing for the run..."

    - name: Gather host environment variables
      ansible.builtin.setup:
        gather_subset:
          - env

  roles:
    - name: Cleanup setup
      role: shiftstack.stages.cleanup

    - name: Prepare setup
      role: shiftstack.stages.create_installer

  post_tasks:
    - name: Add installer_host to the inventory
      ansible.builtin.debug:
        msg: "TBD"


- name: OCP testing for new candidate on legacy OSP (17.1 or 16.2)
  hosts: installer_vm
  gather_facts: no
  # debugger: on_failed # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_debugger.html#playbook-debugger
  vars_files:
    - "../configs/secret.yaml"
    - "../configs/legacy_ocp_testing.yaml"

  pre_tasks:
    - name: Preparing for the run
      ansible.builtin.debug:
        msg: "Preparing for the run..."

    - name: Gather host environment variables
      ansible.builtin.setup:
        gather_subset:
          - env

  roles:
    - name: Prepare
      role: shiftstack.stages.prepare

    - name: Install
      role: shiftstack.stages.install
      vars:
        installation_type: ipi_proxy



