---
- name: OCP testing for new candidate on legacy OSP (17.1 or 16.2)
  hosts: localhost
  gather_facts: no
  # debugger: on_failed # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_debugger.html#playbook-debugger
  vars_files:
    - "../group_vars/all.yml"
    - "../configs/secret.yaml"
    - "../configs/legacy_ocp_testing.yaml"

  pre_tasks:
    - name: Preparing for the run
      ansible.builtin.debug:
        msg: "Preparing for the run..."

    - name: Gather host environment variables
      ansible.builtin.setup:
        gather_subset:
          - env

    - name: Cleanup workspace flags - Remove the stage_unstable_flag if it exists
      file:
        path: "{{ stage_unstable_flag }}"
        state: absent

  roles:
    - name: Discover OSP version
      role: shiftstack.tools.discover_osp_version

    - name: Cleanup setup
      role: shiftstack.stages.cleanup

    - name: Prepare setup
      role: shiftstack.stages.prepare

    - name: Install OCP on setup
      role: shiftstack.stages.install
      vars:
        installation_type: ipi

    - name: Discover OCP version and networkType
      role: shiftstack.tools.discover_ocp_version
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Run post operations and OCP verification checks on setup
      role: shiftstack.stages.post
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Run tests on OCP
      role: shiftstack.stages.test

    - name: Run day2ops
      role: shiftstack.stages.day2ops

  post_tasks:
    - name: Gathering resources
      ansible.builtin.debug:
        msg: "Gathering resources..."
