---
- name: OCP testing for new candidate
  hosts: localhost
  gather_facts: no
  vars_files:
    - "../configs/secret.yaml"
    - "../configs/ocp_testing.yaml"

  pre_tasks:
    - name: Preparing for the run
      ansible.builtin.debug:
        msg: "Preparing for the run..."

    - name: Gather host environment variables
      ansible.builtin.setup:
        gather_subset:
          - env

    - name: Make a copy of the original config directory
      vars:
        home_dir: "{{ ansible_facts.env['HOME'] }}"
      ansible.builtin.copy:
        src: "{{ home_dir }}/.original-config/openstack/"
        dest: "{{ home_dir }}/.config/openstack/"
        remote_src: yes
        mode: u=rw,g=rw,o=r

  roles:
    - name: Cleanup setup
      role: shiftstack.stages.cleanup

    - name: Prepare setup
      role: shiftstack.stages.prepare

    - name: Install OCP on setup
      role: shiftstack.stages.install
      vars:
        installation_type: ipi

    - name: Run post operations on setup
      role: shiftstack.stages.post

    - name: Run post operations on setup
      role: shiftstack.stages.verification

    - name: Run tests on OCP
      role: shiftstack.stages.test

    - name: Run day2ops
      role: shiftstack.stages.day2ops

  post_tasks:
    - name: Gathering resources
      ansible.builtin.debug:
        msg: "Gathering resources..."
