---
- name: Cleanup the OCP setup and prepare the environment for testing OCP on OpenStack 18
  hosts: localhost
  gather_facts: yes
  vars_files:
    - "../configs/global.yml"
  pre_tasks:
    - name: Cleanup workspace flags - Remove the stage_unstable_flag if it exists
      ansible.builtin.file:
        path: "{{ stage_unstable_flag }}"
        state: absent
  tasks:
    - name: Discover the OSP version
      ansible.builtin.include_role:
        name: shiftstack.tools.tools_get_deploy_info
        tasks_from: discover_osp_version.yml

    - name: Cleanup the setup
      ansible.builtin.include_role:
        name: shiftstack.stages.cleanup
      when: "'cleanup' in stages"

    - name: Restore the OpenStack original config directory (includes the clouds.yaml and secure.yaml)
      ansible.builtin.copy:
        src: "{{ home_dir }}/.original-config/openstack/"
        dest: "{{ home_dir }}/.config/openstack/"
        remote_src: yes
        mode: u=rwx,g=rwx,o=rwx
      when: "'cleanup' in stages or 'prepare' in stages"

- name: Prepare the OpenShift environment
  hosts: localhost
  gather_facts: no
  vars_files:
    - "../configs/global.yml"
    - "../configs/secret.yaml"
  tasks:
    - name: Prepare setup for OCP installation
      ansible.builtin.include_role:
        name: shiftstack.stages.prepare
      when: "'prepare' in stages"

    - name: Update the Ansible inventory in case not deploying an installer host
      ansible.builtin.include_role:
        name: shiftstack.tools.tools_ansible_inventory
        tasks_from: create_installer_group.yml
      when: "not deploy_installer_host"

- name: Prepare the OpenShift installer
  ansible.builtin.import_playbook: plays/prepare.yaml
  when: "'prepare' in stages"

- name: Install OpenShift
  ansible.builtin.import_playbook: plays/install.yaml
  when: "'install' in stages"

- name: Discover OCP version and networkType
  hosts: installer
  gather_facts: no
  vars_files:
    - "../configs/global.yml"
  tasks:
    - name: Discover OCP version and networkType
      ansible.builtin.include_role:
        name: shiftstack.tools.tools_get_deploy_info
        tasks_from: discover_ocp_version.yml

- name: GPU-Installation
  ansible.builtin.import_playbook: plays/gpu.yaml
  when: "'gpu' in stages"

- name: Post-Installation
  ansible.builtin.import_playbook: plays/post_install.yaml
  when: "'post' in stages"

- name: Run OpenShift Verification stage
  ansible.builtin.import_playbook: plays/verification.yaml
  when: "'verification' in stages"

- name: Day2ops OpenShift stage
  ansible.builtin.import_playbook: plays/day2ops.yaml
  when: "'day2ops' in stages"

- name: Run Openstack-Test on OpenShift
  ansible.builtin.import_playbook: plays/openstack_test.yaml
  when: "'openstack_test' in stages"

- name: Run LB-Test on OpenShift
  ansible.builtin.import_playbook: plays/lb_tests.yaml
  when: "'lb_tests' in stages"

- name: Run Openshift Conformance Test on OpenShift
  ansible.builtin.import_playbook: plays/conformance_test.yaml
  when: "'conformance_test' in stages"

- name: Run Openshift Cinder CSI Tests on OpenShift
  ansible.builtin.import_playbook: plays/cinder_csi.yaml
  when: "'cinder_csi_tests' in stages"

- name: Run Openshift Manila CSI Tests on OpenShift
  ansible.builtin.import_playbook: plays/manila_csi.yaml
  when: "'manila_csi_tests' in stages"
