- name: OCP testing for new candidate
  hosts: localhost
  vars_files:
    - "vars/defaults.yaml"
  pre_tasks:
    - name: Preparing for the run
      ansible.builtin.debug:
        msg: "Preparing for the run..."
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

  roles:
    - name: Cleanup setup
      role: shiftstack.stages.cleanup
      vars:
        cleanup_foo: bar # overrides var_files

    - name: Prepare setup
      role: shiftstack.stages.prepare

    - name: Install OCP on setup
      role: shiftstack.stages.install

    - name: Run post operations on setup
      role: shiftstack.stages.post

    - name: Run tests on OCP
      role: shiftstack.stages.test

    - name: Run day2ops
      role: shiftstack.stages.day2ops

  post_tasks:
    - name: Gathering resources
      ansible.builtin.debug:
        msg: "Gathering resources..."
