---
- name: Cleanup the OCP setup and prepare the environment for testing OCP on OpenStack 18
  ansible.builtin.import_playbook: plays/cleanup.yaml

- name: Prepare the OpenShift environment for installation and testing new candidate
  ansible.builtin.import_playbook: plays/prepare.yaml

- name: Install OpenShift new candidate on OSP
  ansible.builtin.import_playbook: plays/install.yaml
  when: "'install' in stages"

- name: Post OpenShift installation stage
  ansible.builtin.import_playbook: plays/post_install.yaml

- name: Verify the OpenShift cluster
  ansible.builtin.import_playbook: plays/verification.yaml
  when: "'verification' in stages"

- name: Day2ops OpenShift stage
  ansible.builtin.import_playbook: plays/day2ops.yaml
  when: "'day2ops' in stages"

- name: Run Openstack-Test on OpenShift
  ansible.builtin.import_playbook: plays/openstack_test.yaml
  when: "'openstack_test' in stages"

- name: Run LB-Test on OpenShift
  ansible.builtin.import_playbook: plays/lb_tests.yaml
  when: "'lb_tests' in stages"

- name: Run Openshift Conformance Test on OpenShift
  ansible.builtin.import_playbook: plays/conformance_test.yaml
  when: "'conformance_test' in stages"

- name: Run Openshift Cinder CSI Tests on OpenShift
  ansible.builtin.import_playbook: plays/cinder_csi.yaml
  when: "'cinder_csi_tests' in stages"

- name: Run Openshift Manila CSI Tests on OpenShift
  ansible.builtin.import_playbook: plays/manila_csi.yaml
  when: "'manila_csi_tests' in stages"
