---
- name: Run OCP verification checks
  hosts: installer
  gather_facts: no
  # debugger: on_failed # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_debugger.html#playbook-debugger
  vars_files:
    - "../configs/global.yml"
    - "../configs/secret.yaml"
    - "../configs/legacy_ocp_testing.yaml"

  environment:
    KUBECONFIG: "{{ kubeconfig }}"

  roles:
    - name: Run OCP verification checks
      role: shiftstack.stages.verification
